[platformio]
src_dir = main

; Common settings for all environments
[env]
monitor_speed = 115200
monitor_filters = direct
board_build.partitions = partitions.csv
extra_scripts = pre:pre_build.py

; ─── ESP32 base (40MHz/QIO/4MB) ─────────────────────────────────────────────
[env:base-esp32]
platform = platformio/espressif32 @ 6.12.0
framework = espidf
board = esp-wrover-kit
board_build.mcu = esp32
board_build.f_cpu = 240000000L
board_build.f_flash = 40000000L
board_build.flash_mode = qio
board_build.flash_size = 4MB
board_upload.flash_size = 4MB
monitor_rts = 0
monitor_dtr = 0

; ─── ESP32-S2 base (80MHz/QIO/4MB) ──────────────────────────────────────────
[env:base-esp32s2]
platform = platformio/espressif32 @ 6.12.0
framework = espidf
board = esp32-s2-saola-1
board_build.mcu = esp32s2
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = dio
board_build.flash_size = 4MB
board_upload.flash_size = 4MB

; ─── ESP32-S3 base (80MHz/QIO/4MB) ──────────────────────────────────────────
[env:base-esp32s3]
platform = platformio/espressif32 @ 6.12.0
framework = espidf
board = esp32-s3-devkitc-1
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.flash_size = 4MB
board_upload.flash_size = 4MB

; ─── ADAU1961 board (ESP32, ADAU1961) ───────────────────────────────────────────
[env:adau1961-esp32]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.adau1961"

; ─── PCM5102A board (ESP32, PCM5102A) ───────────────────────────────────────────
[env:pcm5102a-esp32]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.pcm5102a"

; ─── WT32-ETH01 board (ESP32, PCM5102A, Ethernet) ───────────────────────────────────────────
[env:pcm5102a-wt32-eth01]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.pcm5102a-wt32-eth01"

; ─── Olimex ESP32-POE board (ESP32, PCM5102A, Ethernet) ───────────────────────────────────────────
[env:pcm5102a-olimex-esp32-poe]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.pcm5102a-olimex-esp32-poe"

[env:max98357a-esp32-s2]
extends = env:base-esp32s2
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.max98357a-esp32-s2"

; ─── HiFi-ESP32 (ESP32, PCM5100) ───────────────────────────────────────────
[env:sonocotta-hifi-esp32]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.hifi-esp32"

; ─── HiFi-ESP32-S3 (ESP32-S3, PCM5100) ───────────────────────────────────────────
[env:sonocotta-hifi-esp32s3]
extends = env:base-esp32s3
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.hifi-esp32s3"

; ─── HiFi-Esparagus (ESP32, PCM5100) ───────────────────────────────────────────
[env:sonocotta-hifi-esparagus]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.hifi-esparagus"

; ─── HiFi-Esparagus-S3 (ESP32-S3, PCM5100) ───────────────────────────────────────────
[env:sonocotta-hifi-esparagus-s3]
extends = env:base-esp32s3
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.hifi-esparagus-s3"

; ─── HiFi-ESP32-Plus (ESP32, PCM5122) ───────────────────────────────────────────
[env:sonocotta-hifi-esp32-plus]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.hifi-esp32-plus"

[env:sonocotta-hifi-esp32-plus-debug]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.hifi-esp32-plus;sdkconfig.defaults.debug"
monitor_filters = esp32_exception_decoder

; ─── HiFi-ESP32-S3-Plus (ESP32-S3, PCM5122) ───────────────────────────────────────────
[env:sonocotta-hifi-esp32s3-plus]
extends = env:base-esp32s3
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.hifi-esp32s3-plus"

; ─── Loud-ESP32 (ESP32, MAX98357A) ───────────────────────────────────────────
[env:sonocotta-loud-esp32]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.loud-esp32"

; ─── Loud-ESP32-S3 (ESP32-S3, MAX98357A) ───────────────────────────────────────────
[env:sonocotta-loud-esp32s3]
extends = env:base-esp32s3
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.loud-esp32s3"

; ─── Loud-Esparagus (ESP32, MAX98357A) ───────────────────────────────────────────
[env:sonocotta-loud-esparagus]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.loud-esparagus"

; ─── Esparagus-Echo (ESP32-S3, MAX98357A) ───────────────────────────────────────────
[env:sonocotta-esparagus-echo]
extends = env:base-esp32s3
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.esparagus-echo-s3"

; ─── Loud-ESP32-Plus (ESP32, MA12070P) ───────────────────────────────────────────
[env:sonocotta-loud-esp32-plus]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.loud-esp32-plus"

; ─── Loud-ESP32-S3-Plus (ESP32-S3, MA12070P) ───────────────────────────────────────────
[env:sonocotta-loud-esp32-s3-plus]
extends = env:base-esp32s3
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.loud-esp32s3-plus"

; ─── Louder-ESP32 (ESP32, TAS5805M) ────────────────────────────────────────────────
[env:sonocotta-louder-esp32]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.louder-esp32"

; ─── Louder-ESP32-S3 (ESP32-S3, TAS5805M) ────────────────────────────────────────────────
[env:sonocotta-louder-esp32-s3]
extends = env:base-esp32s3
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.louder-esp32s3"

; ─── Louder-Esparagus (ESP32, TAS5805M) ────────────────────────────────────────────────
[env:sonocotta-louder-esparagus]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.louder-esparagus"

; ─── Louder-ESP32-Plus (ESP32, TAS5825M) ────────────────────────────────────────────────
[env:sonocotta-louder-esp32-plus]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.louder-esp32-plus"

; ─── Louder-ESP32-S3-Plus (ESP32-S3, TAS5825M) ────────────────────────────────────────────────
[env:sonocotta-louder-esp32-s3-plus]
extends = env:base-esp32s3
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.louder-esp32s3-plus"

; ─── Esparagus Audio Brick (ESP32, TAS5825M) ───────────────────────────────────────────
[env:sonocotta-esparagus-audio-brick]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.audio-brick-esp32"

; ─── Esparagus Audio Brick DEBUG (ESP32, TAS5825M) ─────────────────────────────────────
; [env:sonocotta-esparagus-audio-brick-debug]
; extends = env:sonocotta-esparagus-audio-brick
; board_build.cmake_extra_args =
;     "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.audio-brick-esp32;sdkconfig.defaults.debug"
; monitor_filters = esp32_exception_decoder

; ─── Esparagus Audio Brick (ESP32-S3, TAS5825M) ────────────────────────────────────────
[env:sonocotta-esparagus-audio-brick-s3]
extends = env:base-esp32s3
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.audio-brick-esp32s3"

; ─── Amped-ESP32 (ESP32, PCM5100, TPA31XX amp) ───────────────────────────────────────────
[env:sonocotta-amped-esp32]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.amped-esp32"

; ─── Amped-ESP32-S3 (ESP32-S3, PCM510, TPA31XX amp) ───────────────────────────────────────────
[env:sonocotta-amped-esp32s3]
extends = env:base-esp32s3
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.amped-esp32s3"

; ─── Amped-Esparagus (ESP32, PCM5100, TPA31XX amp) ───────────────────────────────────────────
[env:sonocotta-amped-esparagus]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.amped-esparagus"

; ─── Amped-ESP32-Plus (ESP32, PCM5122, TPA31XX amp) ───────────────────────────────────────────
[env:sonocotta-amped-esp32-plus]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.amped-esp32-plus"

[env:sonocotta-amped-esp32-plus-debug]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.amped-esp32-plus;sdkconfig.defaults.debug"
monitor_filters = esp32_exception_decoder

; ─── Amped-ESP32-S3-Plus (ESP32-S3, PCM5122, TPA31XX amp) ───────────────────────────────────────────
[env:sonocotta-amped-esp32s3-plus]
extends = env:base-esp32s3
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults.amped-esp32s3-plus"

; ─── AI-Thinker ESP32-A1S-AudioKit (ESP32, ES8388) ───────────────────────────────────────────
[env:ai-thinker-esp32-a1s-audiokit]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.ai-thinker-esp32-a1s-audiokit"

; ─── Espressif Lyra T 4.2 (ESP32, ES8388) ───────────────────────────────────────────
[env:espressif-lyra-t-42]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.espressif-lyra-t-42"

; ─── Espressif Lyra T 4.3 (ESP32, ES8388) ───────────────────────────────────────────
[env:espressif-lyra-t-43]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.espressif-lyra-t-43"

; ─── Espressif Lyra T Mini (ESP32, ES8311) ───────────────────────────────────────────
[env:espressif-lyra-t-mini]
extends = env:base-esp32
board_build.cmake_extra_args =
    "-DSDKCONFIG_DEFAULTS=sdkconfig.defaults;sdkconfig.defaults_psram;sdkconfig.defaults.espressif-lyra-t-mini"
