"""
Pre-build script: generate EMBED_FILES / EMBED_TXTFILES assembly stubs.

ESP-IDF converts embedded binary/text files into assembly stubs (e.g.
favicon.ico.S) via CMake CUSTOM_COMMANDs.  PlatformIO skips those commands
because it drives ninja directly on object-file targets.  This script runs
`cmake --build . --target <name>.S` for every such stub before ninja starts,
so the source files exist when the assembler is invoked.
"""

import subprocess
import os
import re

Import("env")  # noqa: F821  (PlatformIO injects this)


def generate_embedded_stubs():
    build_dir = env.subst("$BUILD_DIR")
    ninja_file = os.path.join(build_dir, "build.ninja")

    if not os.path.isfile(ninja_file):
        # build.ninja is generated by cmake configure, which runs *after*
        # extra_scripts are evaluated on the very first clean build.  Skip
        # here — the CI workflow (and second local run) will pick it up.
        print("pre_build.py: build.ninja not found (first clean build) — "
              "skipping stub generation; retry the build to succeed.")
        return

    # Find all *.S targets produced by CUSTOM_COMMAND (the embed stubs) along
    # with their source data file.  In build.ninja they appear as:
    #   build foo.ico.S | ...: CUSTOM_COMMAND /abs/path/to/foo.ico /abs/.../embed_asm.cmake || ...
    # The explicit dependency that is NOT the cmake helper script is the
    # original asset, so we can compare its mtime against the generated stub.
    stub_pattern = re.compile(
        r"^build ([^|:\s]+\.S)(?:\s*\|[^:]*)?:\s*CUSTOM_COMMAND\s+(.*?)(?:\s*\|\||$)"
    )
    stubs = []  # list of (stub_relpath, source_abspath_or_None)
    with open(ninja_file) as f:
        for line in f:
            m = stub_pattern.match(line)
            if not m:
                continue
            deps = m.group(2).split()
            source = next(
                (d for d in deps if not d.endswith(".cmake") and os.path.isfile(d)),
                None,
            )
            stubs.append((m.group(1), source))

    if not stubs:
        return

    for stub, source in stubs:
        full_path = os.path.join(build_dir, stub)

        # Regenerate when the stub is missing, or when its source asset has
        # been edited since the stub was last generated.  PlatformIO does not
        # re-run the embed CUSTOM_COMMANDs on its own, so without this check an
        # edited HTML/JS/CSS asset would silently keep linking a stale copy.
        if os.path.isfile(full_path):
            if source is None:
                continue  # can't determine freshness; leave existing stub
            if os.path.getmtime(source) <= os.path.getmtime(full_path):
                continue  # stub is up to date
            # Source is newer — drop the stale stub so cmake/ninja rebuilds it.
            print(f"pre_build.py: {stub} is stale (source changed) — regenerating ...")
            os.remove(full_path)
        else:
            print(f"pre_build.py: generating {stub} ...")

        result = subprocess.run(
            ["cmake", "--build", ".", "--target", stub],
            cwd=build_dir,
        )
        if result.returncode != 0:
            print(f"pre_build.py: WARNING — cmake failed to generate {stub} "
                  f"(exit {result.returncode})")


generate_embedded_stubs()
