/*
 * MIT License
 *
 * Copyright (c) 2021 David Douard <david.douard@sdfa3.org>
 *
 * Permission is hereby granted for use on all ESPRESSIF SYSTEMS products, in
 * which case, it is free of charge, to any person obtaining a copy of this
 * software and associated documentation files (the "Software"), to deal in the
 * Software without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
 * the Software, and to permit persons to whom the Software is furnished to do
 * so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

#ifndef _PCM51XX_REG_CFG_
#define _PCM51XX_REG_CFG_

#include "pcm51xx.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
  uint8_t offset;
  uint8_t value;
} pcm51xx_cfg_reg_t;

static const pcm51xx_cfg_reg_t pcm51xx_init_seq[] = {

    // EXIT SHUTDOWN STATE
    { PCM51XX_BOOK_00, PCM51XX_PAGE_00  },  // SELECT PAGE 0
     // CONFIGURE AUDIO PATHS
    { PCM51XX_REG_MUTE, 0x00  },            // UNMUTE
    { PCM51XX_REG_DATA_PATH, 0x11  },       // DAC DATA PATH L->ch1, R->ch2
    { PCM51XX_REG_PLL, 0x10  },             // BCK as SRC for PLL
    { PCM51XX_REG_CLKDET, 0x08  },          // IGNORE MISSING MCLK
    { PCM51XX_REG_VOL_L, 0x30  },           // DIGITAL VOLUME L
    { PCM51XX_REG_VOL_R, 0x30  },           // DIGITAL VOLUME R
    { PCM51XX_REG_PMOD, PCM51XX_PMOD_NORMAL  },  // DISABLE STBY
};

// static const pcm51xx_cfg_reg_t _pcm51xx_dsp_init_seq[] = {
//     { PCM51XX_REG_PMOD, PCM51XX_PMOD_STANDBY  },  // STBY
//     { PCM51XX_REG_PROCESS_FLOW, PCM51XX_PROC_FLOW_5 },  
//     { PCM51XX_REG_X16INTP, 0x00  },        // DISABLE X16 INTERPOLATION
//     { PCM51XX_REG_PMOD, PCM51XX_PMOD_NORMAL  },  // DISABLE STBY
// };

// static const pcm51xx_cfg_reg_t _pcm51xx_dsp_uninit_seq[] = {
//     { PCM51XX_REG_PMOD, PCM51XX_PMOD_STANDBY  },  // STBY
//     { PCM51XX_REG_PROCESS_FLOW, PCM51XX_PROC_FLOW_1 },  
//     { PCM51XX_REG_X16INTP, 0x00  },        // DISABLE X16 INTERPOLATION
//     { PCM51XX_REG_PMOD, PCM51XX_PMOD_NORMAL  },  // DISABLE STBY
// };

/* Auto-generated by cfg_to_c_array.py
 * Source: I2C writes to address 0x98
 * Delay commands omitted (reset is handled outside this sequence).
 */

static const pcm51xx_cfg_reg_t pcm51xx_dsp_init_seq[] = {
    { 0x00, 0x00 },              /* ------ Page 0 ---------------------------------------------... */
    { 0x02, 0x10 },              /* Set Stand-by mode */
    { 0x00, 0x2C },              /* ----------- Page 44  ------------------------------------... */
    // { 0x08, 0xFF },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 0 */
    // { 0x09, 0xFF },              /* (Bit 23-16) */
    // { 0x0A, 0xFF },              /* (Bit 15-8) */
    // { 0x0B, 0x00 },              /* (Bit 7-0) */
    // { 0x0C, 0x80 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 1 */
    // { 0x0D, 0x00 },              /* (Bit 23-16) */
    // { 0x0E, 0x00 },              /* (Bit 15-8) */
    // { 0x0F, 0x00 },              /* (Bit 7-0) */
    // { 0x10, 0x40 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 2 */
    // { 0x11, 0x00 },              /* (Bit 23-16) */
    // { 0x12, 0x00 },              /* (Bit 15-8) */
    // { 0x13, 0x00 },              /* (Bit 7-0) */
    // { 0x14, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 3 */
    // { 0x15, 0xFF },              /* (Bit 23-16) */
    // { 0x16, 0xFF },              /* (Bit 15-8) */
    // { 0x17, 0x00 },              /* (Bit 7-0) */
    // { 0x18, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 4 */
    // { 0x19, 0x00 },              /* (Bit 23-16) */
    // { 0x1A, 0x00 },              /* (Bit 15-8) */
    // { 0x1B, 0x00 },              /* (Bit 7-0) */
    // { 0x1C, 0x1A },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 5 */
    // { 0x1D, 0x00 },              /* (Bit 23-16) */
    // { 0x1E, 0x00 },              /* (Bit 15-8) */
    // { 0x1F, 0x00 },              /* (Bit 7-0) */
    // { 0x20, 0x11 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 6 */
    // { 0x21, 0x80 },              /* (Bit 23-16) */
    // { 0x22, 0x00 },              /* (Bit 15-8) */
    // { 0x23, 0x00 },              /* (Bit 7-0) */
    // { 0x24, 0x28 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 7 */
    // { 0x25, 0x00 },              /* (Bit 23-16) */
    // { 0x26, 0x00 },              /* (Bit 15-8) */
    // { 0x27, 0x00 },              /* (Bit 7-0) */
    // { 0x28, 0x27 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 8 */
    // { 0x29, 0x80 },              /* (Bit 23-16) */
    // { 0x2A, 0x00 },              /* (Bit 15-8) */
    // { 0x2B, 0x00 },              /* (Bit 7-0) */
    // { 0x2C, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 9 */
    // { 0x2D, 0xFF },              /* (Bit 23-16) */
    // { 0x2E, 0xFF },              /* (Bit 15-8) */
    // { 0x2F, 0x00 },              /* (Bit 7-0) */
    { 0x30, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 10 */
    { 0x31, 0xff },              /* (Bit 23-16) */
    { 0x32, 0xff },              /* (Bit 15-8) */
    { 0x33, 0x00 },              /* (Bit 7-0) */
    { 0x34, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 11 */
    { 0x35, 0x00 },              /* (Bit 23-16) */
    { 0x36, 0x00 },              /* (Bit 15-8) */
    { 0x37, 0x00 },              /* (Bit 7-0) */
    { 0x38, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 12 */
    { 0x39, 0x00 },              /* (Bit 23-16) */
    { 0x3A, 0x00 },              /* (Bit 15-8) */
    { 0x3B, 0x00 },              /* (Bit 7-0) */
    { 0x3C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 13 */
    { 0x3D, 0x00 },              /* (Bit 23-16) */
    { 0x3E, 0x00 },              /* (Bit 15-8) */
    { 0x3F, 0x00 },              /* (Bit 7-0) */
    { 0x40, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 14 */
    { 0x41, 0x00 },              /* (Bit 23-16) */
    { 0x42, 0x00 },              /* (Bit 15-8) */
    { 0x43, 0x00 },              /* (Bit 7-0) */
    { 0x44, 0x7f },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 15 */
    { 0x45, 0xff },              /* (Bit 23-16) */
    { 0x46, 0xff },              /* (Bit 15-8) */
    { 0x47, 0x00 },              /* (Bit 7-0) */
    { 0x48, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 16 */
    { 0x49, 0x00 },              /* (Bit 23-16) */
    { 0x4A, 0x00 },              /* (Bit 15-8) */
    { 0x4B, 0x00 },              /* (Bit 7-0) */
    { 0x4C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 17 */
    { 0x4D, 0x00 },              /* (Bit 23-16) */
    { 0x4E, 0x00 },              /* (Bit 15-8) */
    { 0x4F, 0x00 },              /* (Bit 7-0) */
    { 0x50, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 18 */
    { 0x51, 0x00 },              /* (Bit 23-16) */
    { 0x52, 0x00 },              /* (Bit 15-8) */
    { 0x53, 0x00 },              /* (Bit 7-0) */
    { 0x54, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 19 */
    { 0x55, 0x00 },              /* (Bit 23-16) */
    { 0x56, 0x00 },              /* (Bit 15-8) */
    { 0x57, 0x00 },              /* (Bit 7-0) */
    { 0x58, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 20 */
    { 0x59, 0xff },              /* (Bit 23-16) */
    { 0x5A, 0xff },              /* (Bit 15-8) */
    { 0x5B, 0x00 },              /* (Bit 7-0) */
    { 0x5C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 21 */
    { 0x5D, 0x00 },              /* (Bit 23-16) */
    { 0x5E, 0x00 },              /* (Bit 15-8) */
    { 0x5F, 0x00 },              /* (Bit 7-0) */
    { 0x60, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 22 */
    { 0x61, 0x00 },              /* (Bit 23-16) */
    { 0x62, 0x00 },              /* (Bit 15-8) */
    { 0x63, 0x00 },              /* (Bit 7-0) */
    { 0x64, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 23 */
    { 0x65, 0x00 },              /* (Bit 23-16) */
    { 0x66, 0x00 },              /* (Bit 15-8) */
    { 0x67, 0x00 },              /* (Bit 7-0) */
    { 0x68, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 24 */
    { 0x69, 0x00 },              /* (Bit 23-16) */
    { 0x6A, 0x00 },              /* (Bit 15-8) */
    { 0x6B, 0x00 },              /* (Bit 7-0) */
    { 0x6C, 0x7f },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 25 */
    { 0x6D, 0xff },              /* (Bit 23-16) */
    { 0x6E, 0xff },              /* (Bit 15-8) */
    { 0x6F, 0x00 },              /* (Bit 7-0) */
    { 0x70, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 26 */
    { 0x71, 0x00 },              /* (Bit 23-16) */
    { 0x72, 0x00 },              /* (Bit 15-8) */
    { 0x73, 0x00 },              /* (Bit 7-0) */
    { 0x74, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 27 */
    { 0x75, 0x00 },              /* (Bit 23-16) */
    { 0x76, 0x00 },              /* (Bit 15-8) */
    { 0x77, 0x00 },              /* (Bit 7-0) */
    { 0x78, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 28 */
    { 0x79, 0x00 },              /* (Bit 23-16) */
    { 0x7A, 0x00 },              /* (Bit 15-8) */
    { 0x7B, 0x00 },              /* (Bit 7-0) */
    { 0x7C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 29 */
    { 0x7D, 0x00 },              /* (Bit 23-16) */
    { 0x7E, 0x00 },              /* (Bit 15-8) */
    { 0x7F, 0x00 },              /* (Bit 7-0) */
    { 0x00, 0x2D },              /* ----------- Page 45 --------------------------------------... */
    { 0x08, 0x7f },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 30 */
    { 0x09, 0xff },              /* (Bit 23-16) */
    { 0x0A, 0xff },              /* (Bit 15-8) */
    { 0x0B, 0x00 },              /* (Bit 7-0) */
    { 0x0C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 31 */
    { 0x0D, 0x00 },              /* (Bit 23-16) */
    { 0x0E, 0x00 },              /* (Bit 15-8) */
    { 0x0F, 0x00 },              /* (Bit 7-0) */
    { 0x10, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 32 */
    { 0x11, 0x00 },              /* (Bit 23-16) */
    { 0x12, 0x00 },              /* (Bit 15-8) */
    { 0x13, 0x00 },              /* (Bit 7-0) */
    { 0x14, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 33 */
    { 0x15, 0x00 },              /* (Bit 23-16) */
    { 0x16, 0x00 },              /* (Bit 15-8) */
    { 0x17, 0x00 },              /* (Bit 7-0) */
    { 0x18, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 34 */
    { 0x19, 0x00 },              /* (Bit 23-16) */
    { 0x1A, 0x00 },              /* (Bit 15-8) */
    { 0x1B, 0x00 },              /* (Bit 7-0) */
    { 0x1C, 0x7f },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 35 */
    { 0x1D, 0xff },              /* (Bit 23-16) */
    { 0x1E, 0xff },              /* (Bit 15-8) */
    { 0x1F, 0x00 },              /* (Bit 7-0) */
    { 0x20, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 36 */
    { 0x21, 0x00 },              /* (Bit 23-16) */
    { 0x22, 0x00 },              /* (Bit 15-8) */
    { 0x23, 0x00 },              /* (Bit 7-0) */
    { 0x24, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 37 */
    { 0x25, 0x00 },              /* (Bit 23-16) */
    { 0x26, 0x00 },              /* (Bit 15-8) */
    { 0x27, 0x00 },              /* (Bit 7-0) */
    { 0x28, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 38 */
    { 0x29, 0x00 },              /* (Bit 23-16) */
    { 0x2A, 0x00 },              /* (Bit 15-8) */
    { 0x2B, 0x00 },              /* (Bit 7-0) */
    { 0x2C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 39 */
    { 0x2D, 0x00 },              /* (Bit 23-16) */
    { 0x2E, 0x00 },              /* (Bit 15-8) */
    { 0x2F, 0x00 },              /* (Bit 7-0) */
    { 0x30, 0x7f },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 40 */
    { 0x31, 0xff },              /* (Bit 23-16) */
    { 0x32, 0xff },              /* (Bit 15-8) */
    { 0x33, 0x00 },              /* (Bit 7-0) */
    { 0x34, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 41 */
    { 0x35, 0x00 },              /* (Bit 23-16) */
    { 0x36, 0x00 },              /* (Bit 15-8) */
    { 0x37, 0x00 },              /* (Bit 7-0) */
    { 0x38, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 42 */
    { 0x39, 0x00 },              /* (Bit 23-16) */
    { 0x3A, 0x00 },              /* (Bit 15-8) */
    { 0x3B, 0x00 },              /* (Bit 7-0) */
    { 0x3C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 43 */
    { 0x3D, 0x00 },              /* (Bit 23-16) */
    { 0x3E, 0x00 },              /* (Bit 15-8) */
    { 0x3F, 0x00 },              /* (Bit 7-0) */
    { 0x40, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 44 */
    { 0x41, 0x00 },              /* (Bit 23-16) */
    { 0x42, 0x00 },              /* (Bit 15-8) */
    { 0x43, 0x00 },              /* (Bit 7-0) */
    { 0x44, 0x7f },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 45 */
    { 0x45, 0xff },              /* (Bit 23-16) */
    { 0x46, 0xff },              /* (Bit 15-8) */
    { 0x47, 0x00 },              /* (Bit 7-0) */
    { 0x48, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 46 */
    { 0x49, 0x00 },              /* (Bit 23-16) */
    { 0x4A, 0x00 },              /* (Bit 15-8) */
    { 0x4B, 0x00 },              /* (Bit 7-0) */
    { 0x4C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 47 */
    { 0x4D, 0x00 },              /* (Bit 23-16) */
    { 0x4E, 0x00 },              /* (Bit 15-8) */
    { 0x4F, 0x00 },              /* (Bit 7-0) */
    { 0x50, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 48 */
    { 0x51, 0x00 },              /* (Bit 23-16) */
    { 0x52, 0x00 },              /* (Bit 15-8) */
    { 0x53, 0x00 },              /* (Bit 7-0) */
    { 0x54, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 49 */
    { 0x55, 0x00 },              /* (Bit 23-16) */
    { 0x56, 0x00 },              /* (Bit 15-8) */
    { 0x57, 0x00 },              /* (Bit 7-0) */
    { 0x58, 0x7f },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 50 */
    { 0x59, 0xff },              /* (Bit 23-16) */
    { 0x5A, 0xff },              /* (Bit 15-8) */
    { 0x5B, 0x00 },              /* (Bit 7-0) */
    { 0x5C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 51 */
    { 0x5D, 0x00 },              /* (Bit 23-16) */
    { 0x5E, 0x00 },              /* (Bit 15-8) */
    { 0x5F, 0x00 },              /* (Bit 7-0) */
    { 0x60, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 52 */
    { 0x61, 0x00 },              /* (Bit 23-16) */
    { 0x62, 0x00 },              /* (Bit 15-8) */
    { 0x63, 0x00 },              /* (Bit 7-0) */
    { 0x64, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 53 */
    { 0x65, 0x00 },              /* (Bit 23-16) */
    { 0x66, 0x00 },              /* (Bit 15-8) */
    { 0x67, 0x00 },              /* (Bit 7-0) */
    { 0x68, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 54 */
    { 0x69, 0x00 },              /* (Bit 23-16) */
    { 0x6A, 0x00 },              /* (Bit 15-8) */
    { 0x6B, 0x00 },              /* (Bit 7-0) */
    { 0x6C, 0x7f },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 55 */
    { 0x6D, 0xff },              /* (Bit 23-16) */
    { 0x6E, 0xff },              /* (Bit 15-8) */
    { 0x6F, 0x00 },              /* (Bit 7-0) */
    { 0x70, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 56 */
    { 0x71, 0x00 },              /* (Bit 23-16) */
    { 0x72, 0x00 },              /* (Bit 15-8) */
    { 0x73, 0x00 },              /* (Bit 7-0) */
    { 0x74, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 57 */
    { 0x75, 0x00 },              /* (Bit 23-16) */
    { 0x76, 0x00 },              /* (Bit 15-8) */
    { 0x77, 0x00 },              /* (Bit 7-0) */
    { 0x78, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 58 */
    { 0x79, 0x00 },              /* (Bit 23-16) */
    { 0x7A, 0x00 },              /* (Bit 15-8) */
    { 0x7B, 0x00 },              /* (Bit 7-0) */
    { 0x7C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 59 */
    { 0x7D, 0x00 },              /* (Bit 23-16) */
    { 0x7E, 0x00 },              /* (Bit 15-8) */
    { 0x7F, 0x00 },              /* (Bit 7-0) */
    { 0x00, 0x2E },              /* ----------- Page 46 ----------------------------------------... */
    { 0x08, 0x7f },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 60 */
    { 0x09, 0xff },              /* (Bit 23-16) */
    { 0x0A, 0xff },              /* (Bit 15-8) */
    { 0x0B, 0x00 },              /* (Bit 7-0) */
    { 0x0C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 61 */
    { 0x0D, 0x00 },              /* (Bit 23-16) */
    { 0x0E, 0x00 },              /* (Bit 15-8) */
    { 0x0F, 0x00 },              /* (Bit 7-0) */
    { 0x10, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 62 */
    { 0x11, 0x00 },              /* (Bit 23-16) */
    { 0x12, 0x00 },              /* (Bit 15-8) */
    { 0x13, 0x00 },              /* (Bit 7-0) */
    { 0x14, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 63 */
    { 0x15, 0x00 },              /* (Bit 23-16) */
    { 0x16, 0x00 },              /* (Bit 15-8) */
    { 0x17, 0x00 },              /* (Bit 7-0) */
    { 0x18, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 64 */
    { 0x19, 0x00 },              /* (Bit 23-16) */
    { 0x1A, 0x00 },              /* (Bit 15-8) */
    { 0x1B, 0x00 },              /* (Bit 7-0) */
    { 0x1C, 0x7f },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 65 */
    { 0x1D, 0xff },              /* (Bit 23-16) */
    { 0x1E, 0xff },              /* (Bit 15-8) */
    { 0x1F, 0x00 },              /* (Bit 7-0) */
    { 0x20, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 66 */
    { 0x21, 0x00 },              /* (Bit 23-16) */
    { 0x22, 0x00 },              /* (Bit 15-8) */
    { 0x23, 0x00 },              /* (Bit 7-0) */
    { 0x24, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 67 */
    { 0x25, 0x00 },              /* (Bit 23-16) */
    { 0x26, 0x00 },              /* (Bit 15-8) */
    { 0x27, 0x00 },              /* (Bit 7-0) */
    { 0x28, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 68 */
    { 0x29, 0x00 },              /* (Bit 23-16) */
    { 0x2A, 0x00 },              /* (Bit 15-8) */
    { 0x2B, 0x00 },              /* (Bit 7-0) */
    { 0x2C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 69 */
    { 0x2D, 0x00 },              /* (Bit 23-16) */
    { 0x2E, 0x00 },              /* (Bit 15-8) */
    { 0x2F, 0x00 },              /* (Bit 7-0) */
    { 0x30, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 70 */
    { 0x31, 0x00 },              /* (Bit 23-16) */
    { 0x32, 0xAF },              /* (Bit 15-8) */
    { 0x33, 0x00 },              /* (Bit 7-0) */
    { 0x34, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 71 */
    { 0x35, 0xFF },              /* (Bit 23-16) */
    { 0x36, 0x51 },              /* (Bit 15-8) */
    { 0x37, 0x00 },              /* (Bit 7-0) */
    { 0x38, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 72 */
    { 0x39, 0x02 },              /* (Bit 23-16) */
    { 0x3A, 0xBB },              /* (Bit 15-8) */
    { 0x3B, 0x00 },              /* (Bit 7-0) */
    { 0x3C, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 73 */
    { 0x3D, 0xFD },              /* (Bit 23-16) */
    { 0x3E, 0x45 },              /* (Bit 15-8) */
    { 0x3F, 0x00 },              /* (Bit 7-0) */
    { 0x40, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 74 */
    { 0x41, 0x00 },              /* (Bit 23-16) */
    { 0x42, 0x57 },              /* (Bit 15-8) */
    { 0x43, 0x00 },              /* (Bit 7-0) */
    { 0x44, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 75 */
    { 0x45, 0xFF },              /* (Bit 23-16) */
    { 0x46, 0xA9 },              /* (Bit 15-8) */
    { 0x47, 0x00 },              /* (Bit 7-0) */
    { 0x48, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 76 */
    { 0x49, 0x06 },              /* (Bit 23-16) */
    { 0x4A, 0xD3 },              /* (Bit 15-8) */
    { 0x4B, 0x00 },              /* (Bit 7-0) */
    { 0x4C, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 77 */
    { 0x4D, 0xF9 },              /* (Bit 23-16) */
    { 0x4E, 0x2D },              /* (Bit 15-8) */
    { 0x4F, 0x00 },              /* (Bit 7-0) */
    { 0x50, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 78 */
    { 0x51, 0x1B },              /* (Bit 23-16) */
    { 0x52, 0x4C },              /* (Bit 15-8) */
    { 0x53, 0x00 },              /* (Bit 7-0) */
    { 0x54, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 79 */
    { 0x55, 0xE4 },              /* (Bit 23-16) */
    { 0x56, 0xB4 },              /* (Bit 15-8) */
    { 0x57, 0x00 },              /* (Bit 7-0) */
    { 0x58, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 80 */
    { 0x59, 0x03 },              /* (Bit 23-16) */
    { 0x5A, 0x6A },              /* (Bit 15-8) */
    { 0x5B, 0x00 },              /* (Bit 7-0) */
    { 0x5C, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 81 */
    { 0x5D, 0xFC },              /* (Bit 23-16) */
    { 0x5E, 0x96 },              /* (Bit 15-8) */
    { 0x5F, 0x00 },              /* (Bit 7-0) */
    { 0x60, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 82 */
    { 0x61, 0x44 },              /* (Bit 23-16) */
    { 0x62, 0x32 },              /* (Bit 15-8) */
    { 0x63, 0x00 },              /* (Bit 7-0) */
    { 0x64, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 83 */
    { 0x65, 0xBB },              /* (Bit 23-16) */
    { 0x66, 0xCE },              /* (Bit 15-8) */
    { 0x67, 0x00 },              /* (Bit 7-0) */
    { 0x68, 0x01 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 84 */
    { 0x69, 0x0F },              /* (Bit 23-16) */
    { 0x6A, 0xEF },              /* (Bit 15-8) */
    { 0x6B, 0x00 },              /* (Bit 7-0) */
    { 0x6C, 0x7E },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 85 */
    { 0x6D, 0xF0 },              /* (Bit 23-16) */
    { 0x6E, 0x11 },              /* (Bit 15-8) */
    { 0x6F, 0x00 },              /* (Bit 7-0) */
    { 0x70, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 86 */
    { 0x71, 0x22 },              /* (Bit 23-16) */
    { 0x72, 0x1E },              /* (Bit 15-8) */
    { 0x73, 0x00 },              /* (Bit 7-0) */
    { 0x74, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 87 */
    { 0x75, 0xDD },              /* (Bit 23-16) */
    { 0x76, 0xE2 },              /* (Bit 15-8) */
    { 0x77, 0x00 },              /* (Bit 7-0) */
    { 0x78, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 88 */
    { 0x79, 0x00 },              /* (Bit 23-16) */
    { 0x7A, 0x00 },              /* (Bit 15-8) */
    { 0x7B, 0x00 },              /* (Bit 7-0) */
    { 0x7C, 0xF0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 89 */
    { 0x7D, 0x00 },              /* (Bit 23-16) */
    { 0x7E, 0x00 },              /* (Bit 15-8) */
    { 0x7F, 0x00 },              /* (Bit 7-0) */
    { 0x00, 0x2F },              /* ------------ Page 47 --------------------------------------... */
    { 0x08, 0xE4 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 90 */
    { 0x09, 0x00 },              /* (Bit 23-16) */
    { 0x0A, 0x00 },              /* (Bit 15-8) */
    { 0x0B, 0x00 },              /* (Bit 7-0) */
    { 0x0C, 0x32 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 91 */
    { 0x0D, 0x00 },              /* (Bit 23-16) */
    { 0x0E, 0x00 },              /* (Bit 15-8) */
    { 0x0F, 0x00 },              /* (Bit 7-0) */
    { 0x10, 0x14 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 92 */
    { 0x11, 0x00 },              /* (Bit 23-16) */
    { 0x12, 0x00 },              /* (Bit 15-8) */
    { 0x13, 0x00 },              /* (Bit 7-0) */
    { 0x14, 0xFF },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 93 */
    { 0x15, 0x00 },              /* (Bit 23-16) */
    { 0x16, 0x00 },              /* (Bit 15-8) */
    { 0x17, 0x00 },              /* (Bit 7-0) */
    { 0x18, 0xF0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 94 */
    { 0x19, 0x00 },              /* (Bit 23-16) */
    { 0x1A, 0x00 },              /* (Bit 15-8) */
    { 0x1B, 0x00 },              /* (Bit 7-0) */
    { 0x1C, 0xC0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 95 */
    { 0x1D, 0x00 },              /* (Bit 23-16) */
    { 0x1E, 0x00 },              /* (Bit 15-8) */
    { 0x1F, 0x00 },              /* (Bit 7-0) */
    { 0x20, 0x80 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 96 */
    { 0x21, 0x00 },              /* (Bit 23-16) */
    { 0x22, 0x00 },              /* (Bit 15-8) */
    { 0x23, 0x00 },              /* (Bit 7-0) */
    { 0x24, 0x40 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 97 */
    { 0x25, 0x00 },              /* (Bit 23-16) */
    { 0x26, 0x00 },              /* (Bit 15-8) */
    { 0x27, 0x00 },              /* (Bit 7-0) */
    { 0x28, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 98 */
    { 0x29, 0x00 },              /* (Bit 23-16) */
    { 0x2A, 0x00 },              /* (Bit 15-8) */
    { 0x2B, 0x00 },              /* (Bit 7-0) */
    { 0x2C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 99 */
    { 0x2D, 0x00 },              /* (Bit 23-16) */
    { 0x2E, 0x00 },              /* (Bit 15-8) */
    { 0x2F, 0x00 },              /* (Bit 7-0) */
    { 0x30, 0xD7 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 100 */
    { 0x31, 0x41 },              /* (Bit 23-16) */
    { 0x32, 0xA0 },              /* (Bit 15-8) */
    { 0x33, 0x00 },              /* (Bit 7-0) */
    { 0x34, 0xFF },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 101 */
    { 0x35, 0xF0 },              /* (Bit 23-16) */
    { 0x36, 0x00 },              /* (Bit 15-8) */
    { 0x37, 0x00 },              /* (Bit 7-0) */
    { 0x38, 0x88 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 102 */
    { 0x39, 0x00 },              /* (Bit 23-16) */
    { 0x3A, 0x00 },              /* (Bit 15-8) */
    { 0x3B, 0x00 },              /* (Bit 7-0) */
    { 0x3C, 0x18 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 103 */
    { 0x3D, 0x00 },              /* (Bit 23-16) */
    { 0x3E, 0x00 },              /* (Bit 15-8) */
    { 0x3F, 0x00 },              /* (Bit 7-0) */
    { 0x40, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 104 */
    { 0x41, 0x00 },              /* (Bit 23-16) */
    { 0x42, 0x00 },              /* (Bit 15-8) */
    { 0x43, 0x00 },              /* (Bit 7-0) */
    { 0x44, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 105 */
    { 0x45, 0x00 },              /* (Bit 23-16) */
    { 0x46, 0x00 },              /* (Bit 15-8) */
    { 0x47, 0x00 },              /* (Bit 7-0) */
    { 0x48, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 106 */
    { 0x49, 0x00 },              /* (Bit 23-16) */
    { 0x4A, 0x00 },              /* (Bit 15-8) */
    { 0x4B, 0x00 },              /* (Bit 7-0) */
    { 0x4C, 0x30 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 107 */
    { 0x4D, 0x00 },              /* (Bit 23-16) */
    { 0x4E, 0x00 },              /* (Bit 15-8) */
    { 0x4F, 0x00 },              /* (Bit 7-0) */
    { 0x50, 0xD0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 108 */
    { 0x51, 0x00 },              /* (Bit 23-16) */
    { 0x52, 0x00 },              /* (Bit 15-8) */
    { 0x53, 0x00 },              /* (Bit 7-0) */
    { 0x54, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 109 */
    { 0x55, 0x03 },              /* (Bit 23-16) */
    { 0x56, 0x84 },              /* (Bit 15-8) */
    { 0x57, 0x00 },              /* (Bit 7-0) */
    { 0x58, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 110 */
    { 0x59, 0xB2 },              /* (Bit 23-16) */
    { 0x5A, 0x55 },              /* (Bit 15-8) */
    { 0x5B, 0x00 },              /* (Bit 7-0) */
    { 0x5C, 0x0E },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 111 */
    { 0x5D, 0x5B },              /* (Bit 23-16) */
    { 0x5E, 0xDE },              /* (Bit 15-8) */
    { 0x5F, 0x00 },              /* (Bit 7-0) */
    { 0x60, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 112 */
    { 0x61, 0xFF },              /* (Bit 23-16) */
    { 0x62, 0xFF },              /* (Bit 15-8) */
    { 0x63, 0x00 },              /* (Bit 7-0) */
    { 0x64, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 113 */
    { 0x65, 0x00 },              /* (Bit 23-16) */
    { 0x66, 0x00 },              /* (Bit 15-8) */
    { 0x67, 0x00 },              /* (Bit 7-0) */
    { 0x68, 0x02 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 114 */
    { 0x69, 0x00 },              /* (Bit 23-16) */
    { 0x6A, 0x00 },              /* (Bit 15-8) */
    { 0x6B, 0x00 },              /* (Bit 7-0) */
    { 0x6C, 0x20 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 115 */
    { 0x6D, 0x00 },              /* (Bit 23-16) */
    { 0x6E, 0x00 },              /* (Bit 15-8) */
    { 0x6F, 0x00 },              /* (Bit 7-0) */
    { 0x70, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 116 */
    { 0x71, 0x51 },              /* (Bit 23-16) */
    { 0x72, 0x26 },              /* (Bit 15-8) */
    { 0x73, 0x00 },              /* (Bit 7-0) */
    { 0x74, 0x40 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 117 */
    { 0x75, 0x00 },              /* (Bit 23-16) */
    { 0x76, 0x00 },              /* (Bit 15-8) */
    { 0x77, 0x00 },              /* (Bit 7-0) */
    { 0x78, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 118 */
    { 0x79, 0x0C },              /* (Bit 23-16) */
    { 0x7A, 0xDC },              /* (Bit 15-8) */
    { 0x7B, 0x00 },              /* (Bit 7-0) */
    { 0x7C, 0x02 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 119 */
    { 0x7D, 0x00 },              /* (Bit 23-16) */
    { 0x7E, 0x00 },              /* (Bit 15-8) */
    { 0x7F, 0x00 },              /* (Bit 7-0) */
    { 0x00, 0x30 },              /* ------------- Page 48--------------------------------------... */
    { 0x08, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 120 */
    { 0x09, 0x00 },              /* (Bit 23-16) */
    { 0x0A, 0x00 },              /* (Bit 15-8) */
    { 0x0B, 0x00 },              /* (Bit 7-0) */
    { 0x0C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 121 */
    { 0x0D, 0x00 },              /* (Bit 23-16) */
    { 0x0E, 0x00 },              /* (Bit 15-8) */
    { 0x0F, 0x00 },              /* (Bit 7-0) */
    { 0x10, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 122 */
    { 0x11, 0x16 },              /* (Bit 23-16) */
    { 0x12, 0x5A },              /* (Bit 15-8) */
    { 0x13, 0x00 },              /* (Bit 7-0) */
    { 0x14, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 123 */
    { 0x15, 0x37 },              /* (Bit 23-16) */
    { 0x16, 0x56 },              /* (Bit 15-8) */
    { 0x17, 0x00 },              /* (Bit 7-0) */
    { 0x18, 0x10 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 124 */
    { 0x19, 0xA9 },              /* (Bit 23-16) */
    { 0x1A, 0xBF },              /* (Bit 15-8) */
    { 0x1B, 0x00 },              /* (Bit 7-0) */
    { 0x1C, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 125 */
    { 0x1D, 0xFF },              /* (Bit 23-16) */
    { 0x1E, 0xFF },              /* (Bit 15-8) */
    { 0x1F, 0x00 },              /* (Bit 7-0) */
    { 0x20, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 126 */
    { 0x21, 0x00 },              /* (Bit 23-16) */
    { 0x22, 0x00 },              /* (Bit 15-8) */
    { 0x23, 0x00 },              /* (Bit 7-0) */
    { 0x24, 0x02 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 127 */
    { 0x25, 0x00 },              /* (Bit 23-16) */
    { 0x26, 0x00 },              /* (Bit 15-8) */
    { 0x27, 0x00 },              /* (Bit 7-0) */
    { 0x28, 0xE0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 128 */
    { 0x29, 0x00 },              /* (Bit 23-16) */
    { 0x2A, 0x00 },              /* (Bit 15-8) */
    { 0x2B, 0x00 },              /* (Bit 7-0) */
    { 0x2C, 0x0C },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 129 */
    { 0x2D, 0x9E },              /* (Bit 23-16) */
    { 0x2E, 0x80 },              /* (Bit 15-8) */
    { 0x2F, 0x00 },              /* (Bit 7-0) */
    { 0x30, 0xC0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 130 */
    { 0x31, 0x00 },              /* (Bit 23-16) */
    { 0x32, 0x00 },              /* (Bit 15-8) */
    { 0x33, 0x00 },              /* (Bit 7-0) */
    { 0x34, 0x4F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 131 */
    { 0x35, 0x9F },              /* (Bit 23-16) */
    { 0x36, 0x16 },              /* (Bit 15-8) */
    { 0x37, 0x00 },              /* (Bit 7-0) */
    { 0x38, 0x02 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 132 */
    { 0x39, 0x00 },              /* (Bit 23-16) */
    { 0x3A, 0x00 },              /* (Bit 15-8) */
    { 0x3B, 0x00 },              /* (Bit 7-0) */
    { 0x3C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 133 */
    { 0x3D, 0x00 },              /* (Bit 23-16) */
    { 0x3E, 0x00 },              /* (Bit 15-8) */
    { 0x3F, 0x00 },              /* (Bit 7-0) */
    { 0x40, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 134 */
    { 0x41, 0x00 },              /* (Bit 23-16) */
    { 0x42, 0x00 },              /* (Bit 15-8) */
    { 0x43, 0x00 },              /* (Bit 7-0) */
    { 0x44, 0x20 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 135 */
    { 0x45, 0x00 },              /* (Bit 23-16) */
    { 0x46, 0x00 },              /* (Bit 15-8) */
    { 0x47, 0x00 },              /* (Bit 7-0) */
    { 0x48, 0x40 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 136 */
    { 0x49, 0x00 },              /* (Bit 23-16) */
    { 0x4A, 0x00 },              /* (Bit 15-8) */
    { 0x4B, 0x00 },              /* (Bit 7-0) */
    { 0x4C, 0xE0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 137 */
    { 0x4D, 0x00 },              /* (Bit 23-16) */
    { 0x4E, 0x00 },              /* (Bit 15-8) */
    { 0x4F, 0x00 },              /* (Bit 7-0) */
    { 0x50, 0xC0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 138 */
    { 0x51, 0x00 },              /* (Bit 23-16) */
    { 0x52, 0x00 },              /* (Bit 15-8) */
    { 0x53, 0x00 },              /* (Bit 7-0) */
    { 0x54, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 139 */
    { 0x55, 0x00 },              /* (Bit 23-16) */
    { 0x56, 0x00 },              /* (Bit 15-8) */
    { 0x57, 0x00 },              /* (Bit 7-0) */
    { 0x58, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 140 */
    { 0x59, 0x00 },              /* (Bit 23-16) */
    { 0x5A, 0x00 },              /* (Bit 15-8) */
    { 0x5B, 0x00 },              /* (Bit 7-0) */
    { 0x5C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 141 */
    { 0x5D, 0x00 },              /* (Bit 23-16) */
    { 0x5E, 0x00 },              /* (Bit 15-8) */
    { 0x5F, 0x00 },              /* (Bit 7-0) */
    { 0x60, 0x80 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 142 */
    { 0x61, 0x00 },              /* (Bit 23-16) */
    { 0x62, 0x00 },              /* (Bit 15-8) */
    { 0x63, 0x00 },              /* (Bit 7-0) */
    { 0x64, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 143 */
    { 0x65, 0xFF },              /* (Bit 23-16) */
    { 0x66, 0xFF },              /* (Bit 15-8) */
    { 0x67, 0x00 },              /* (Bit 7-0) */
    { 0x68, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 144 */
    { 0x69, 0x00 },              /* (Bit 23-16) */
    { 0x6A, 0x00 },              /* (Bit 15-8) */
    { 0x6B, 0x00 },              /* (Bit 7-0) */
    { 0x6C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 145 */
    { 0x6D, 0x00 },              /* (Bit 23-16) */
    { 0x6E, 0x00 },              /* (Bit 15-8) */
    { 0x6F, 0x00 },              /* (Bit 7-0) */
    { 0x70, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 146 */
    { 0x71, 0x00 },              /* (Bit 23-16) */
    { 0x72, 0x00 },              /* (Bit 15-8) */
    { 0x73, 0x00 },              /* (Bit 7-0) */
    { 0x74, 0xC0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 147 */
    { 0x75, 0x00 },              /* (Bit 23-16) */
    { 0x76, 0x00 },              /* (Bit 15-8) */
    { 0x77, 0x00 },              /* (Bit 7-0) */
    { 0x78, 0x4C },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 148 */
    { 0x79, 0xCC },              /* (Bit 23-16) */
    { 0x7A, 0xCD },              /* (Bit 15-8) */
    { 0x7B, 0x00 },              /* (Bit 7-0) */
    { 0x7C, 0x4C },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 149 */
    { 0x7D, 0xCC },              /* (Bit 23-16) */
    { 0x7E, 0xCD },              /* (Bit 15-8) */
    { 0x7F, 0x00 },              /* (Bit 7-0) */
    { 0x00, 0x31 },              /* ------------- Page 49 -------------------------------------... */
    { 0x08, 0x4C },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 150 */
    { 0x09, 0xCC },              /* (Bit 23-16) */
    { 0x0A, 0xCD },              /* (Bit 15-8) */
    { 0x0B, 0x00 },              /* (Bit 7-0) */
    { 0x0C, 0x2E },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 151 */
    { 0x0D, 0x00 },              /* (Bit 23-16) */
    { 0x0E, 0x00 },              /* (Bit 15-8) */
    { 0x0F, 0x00 },              /* (Bit 7-0) */
    { 0x10, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 152 */
    { 0x11, 0x00 },              /* (Bit 23-16) */
    { 0x12, 0x01 },              /* (Bit 15-8) */
    { 0x13, 0x00 },              /* (Bit 7-0) */
    { 0x14, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 153 */
    { 0x15, 0x00 },              /* (Bit 23-16) */
    { 0x16, 0x00 },              /* (Bit 15-8) */
    { 0x17, 0x00 },              /* (Bit 7-0) */
    { 0x18, 0x40 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 154 */
    { 0x19, 0x00 },              /* (Bit 23-16) */
    { 0x1A, 0x00 },              /* (Bit 15-8) */
    { 0x1B, 0x00 },              /* (Bit 7-0) */
    { 0x1C, 0x40 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 155 */
    { 0x1D, 0x00 },              /* (Bit 23-16) */
    { 0x1E, 0x00 },              /* (Bit 15-8) */
    { 0x1F, 0x00 },              /* (Bit 7-0) */
    { 0x20, 0x41 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 156 */
    { 0x21, 0x80 },              /* (Bit 23-16) */
    { 0x22, 0x00 },              /* (Bit 15-8) */
    { 0x23, 0x00 },              /* (Bit 7-0) */
    { 0x28, 0x20 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 158 */
    { 0x29, 0x13 },              /* (Bit 23-16) */
    { 0x2A, 0x73 },              /* (Bit 15-8) */
    { 0x2B, 0x00 },              /* (Bit 7-0) */
    { 0x2C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 159 */
    { 0x2D, 0x00 },              /* (Bit 23-16) */
    { 0x2E, 0x00 },              /* (Bit 15-8) */
    { 0x2F, 0x00 },              /* (Bit 7-0) */
    { 0x30, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 160 */
    { 0x31, 0x00 },              /* (Bit 23-16) */
    { 0x32, 0x00 },              /* (Bit 15-8) */
    { 0x33, 0x00 },              /* (Bit 7-0) */
    { 0x34, 0xC0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 161 */
    { 0x35, 0x00 },              /* (Bit 23-16) */
    { 0x36, 0x00 },              /* (Bit 15-8) */
    { 0x37, 0x00 },              /* (Bit 7-0) */
    { 0x38, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 162 */
    { 0x39, 0x00 },              /* (Bit 23-16) */
    { 0x3A, 0x00 },              /* (Bit 15-8) */
    { 0x3B, 0x00 },              /* (Bit 7-0) */
    { 0x3C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 163 */
    { 0x3D, 0x00 },              /* (Bit 23-16) */
    { 0x3E, 0x00 },              /* (Bit 15-8) */
    { 0x3F, 0x00 },              /* (Bit 7-0) */
    { 0x40, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 164 */
    { 0x41, 0x00 },              /* (Bit 23-16) */
    { 0x42, 0x00 },              /* (Bit 15-8) */
    { 0x43, 0x00 },              /* (Bit 7-0) */
    { 0x44, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 165 */
    { 0x45, 0x00 },              /* (Bit 23-16) */
    { 0x46, 0x00 },              /* (Bit 15-8) */
    { 0x47, 0x00 },              /* (Bit 7-0) */
    { 0x48, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 166 */
    { 0x49, 0x00 },              /* (Bit 23-16) */
    { 0x4A, 0x00 },              /* (Bit 15-8) */
    { 0x4B, 0x00 },              /* (Bit 7-0) */
    { 0x4C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 167 */
    { 0x4D, 0x00 },              /* (Bit 23-16) */
    { 0x4E, 0x00 },              /* (Bit 15-8) */
    { 0x4F, 0x00 },              /* (Bit 7-0) */
    { 0x50, 0x40 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 168 */
    { 0x51, 0x00 },              /* (Bit 23-16) */
    { 0x52, 0x00 },              /* (Bit 15-8) */
    { 0x53, 0x00 },              /* (Bit 7-0) */
    { 0x54, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 169 */
    { 0x55, 0x00 },              /* (Bit 23-16) */
    { 0x56, 0x00 },              /* (Bit 15-8) */
    { 0x57, 0x00 },              /* (Bit 7-0) */
    { 0x58, 0xFF },              /* Send 0xFFFFFF ------------ MSB DAC COEFF No. 170 */
    { 0x59, 0xFF },
    { 0x5A, 0xFF },
    { 0x5B, 0x00 },
    { 0x5C, 0x80 },              /* Send 0x800000 ------------ MSB DAC COEFF No. 171 */
    { 0x5D, 0x00 },
    { 0x5E, 0x00 },
    { 0x5F, 0x00 },
    { 0x60, 0x40 },              /* Send 0x400000 ------------ MSB DAC COEFF No. 172 */
    { 0x61, 0x00 },
    { 0x62, 0x00 },
    { 0x63, 0x00 },
    { 0x64, 0x7F },              /* Send 0x7FFFFF ------------ MSB DAC COEFF No. 173 */
    { 0x65, 0xFF },
    { 0x66, 0xFF },
    { 0x67, 0x00 },
    { 0x68, 0x00 },              /* Send 0x000000 ------------ MSB DAC COEFF No. 174 */
    { 0x69, 0x00 },
    { 0x6A, 0x00 },
    { 0x6B, 0x00 },
    { 0x6C, 0x1A },              /* Send 0x1A0000 ------------ MSB DAC COEFF No. 175 */
    { 0x6D, 0x00 },
    { 0x6E, 0x00 },
    { 0x6F, 0x00 },
    { 0x70, 0x11 },              /* Send 0x118000 ------------ MSB DAC COEFF No. 176 */
    { 0x71, 0x80 },
    { 0x72, 0x00 },
    { 0x73, 0x00 },
    { 0x74, 0x28 },              /* Send 0x280000 ------------ MSB DAC COEFF No. 177 */
    { 0x75, 0x00 },
    { 0x76, 0x00 },
    { 0x77, 0x00 },
    { 0x78, 0x27 },              /* Send 0x278000 ------------ MSB DAC COEFF No. 178 */
    { 0x79, 0x80 },
    { 0x7A, 0x00 },
    { 0x7B, 0x00 },
    { 0x7C, 0x7F },              /* Send 0x7FFFFF ------------ MSB DAC COEFF No. 179 */
    { 0x7D, 0xFF },
    { 0x7E, 0xFF },
    { 0x7F, 0x00 },
    { 0x00, 0x32 },              /* ------ Page 50 (?) ----------------------------------... */
    { 0x08, 0x2E },              /* Send 0x2E0000 */
    { 0x09, 0x00 },
    { 0x0A, 0x00 },
    { 0x0B, 0x00 },
    { 0x0C, 0x41 },              /* Send 0x418000 */
    { 0x0D, 0x80 },
    { 0x0E, 0x00 },
    { 0x0F, 0x00 },
    // { 0x00, 0x3E },              /* LOAD B BUFFER  ------------------------------------------... */
    // { 0x08, 0xFF },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 256 */
    // { 0x09, 0xFF },              /* (Bit 23-16) */
    // { 0x0A, 0xFF },              /* (Bit 15-8) */
    // { 0x0B, 0x00 },              /* (Bit 7-0) */
    // { 0x0C, 0x80 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 257 */
    // { 0x0D, 0x00 },              /* (Bit 23-16) */
    // { 0x0E, 0x00 },              /* (Bit 15-8) */
    // { 0x0F, 0x00 },              /* (Bit 7-0) */
    // { 0x10, 0x40 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 258 */
    // { 0x11, 0x00 },              /* (Bit 23-16) */
    // { 0x12, 0x00 },              /* (Bit 15-8) */
    // { 0x13, 0x00 },              /* (Bit 7-0) */
    // { 0x14, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 259 */
    // { 0x15, 0xFF },              /* (Bit 23-16) */
    // { 0x16, 0xFF },              /* (Bit 15-8) */
    // { 0x17, 0x00 },              /* (Bit 7-0) */
    // { 0x18, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 260 */
    // { 0x19, 0x00 },              /* (Bit 23-16) */
    // { 0x1A, 0x00 },              /* (Bit 15-8) */
    // { 0x1B, 0x00 },              /* (Bit 7-0) */
    // { 0x1C, 0x1A },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 261 */
    // { 0x1D, 0x00 },              /* (Bit 23-16) */
    // { 0x1E, 0x00 },              /* (Bit 15-8) */
    // { 0x1F, 0x00 },              /* (Bit 7-0) */
    // { 0x20, 0x11 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 262 */
    // { 0x21, 0x80 },              /* (Bit 23-16) */
    // { 0x22, 0x00 },              /* (Bit 15-8) */
    // { 0x23, 0x00 },              /* (Bit 7-0) */
    // { 0x24, 0x28 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 263 */
    // { 0x25, 0x00 },              /* (Bit 23-16) */
    // { 0x26, 0x00 },              /* (Bit 15-8) */
    // { 0x27, 0x00 },              /* (Bit 7-0) */
    // { 0x28, 0x27 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 264 */
    // { 0x29, 0x80 },              /* (Bit 23-16) */
    // { 0x2A, 0x00 },              /* (Bit 15-8) */
    // { 0x2B, 0x00 },              /* (Bit 7-0) */
    // { 0x2C, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 265 */
    // { 0x2D, 0xFF },              /* (Bit 23-16) */
    // { 0x2E, 0xFF },              /* (Bit 15-8) */
    // { 0x2F, 0x00 },              /* (Bit 7-0) */
    // { 0x30, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 266 */
    // { 0x31, 0x95 },              /* (Bit 23-16) */
    // { 0x32, 0x1C },              /* (Bit 15-8) */
    // { 0x33, 0x00 },              /* (Bit 7-0) */
    // { 0x34, 0xC0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 267 */
    // { 0x35, 0x35 },              /* (Bit 23-16) */
    // { 0x36, 0x72 },              /* (Bit 15-8) */
    // { 0x37, 0x00 },              /* (Bit 7-0) */
    // { 0x38, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 268 */
    // { 0x39, 0x00 },              /* (Bit 23-16) */
    // { 0x3A, 0x00 },              /* (Bit 15-8) */
    // { 0x3B, 0x00 },              /* (Bit 7-0) */
    // { 0x3C, 0x3F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 269 */
    // { 0x3D, 0x95 },              /* (Bit 23-16) */
    // { 0x3E, 0x1D },              /* (Bit 15-8) */
    // { 0x3F, 0x00 },              /* (Bit 7-0) */
    // { 0x40, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 270 */
    // { 0x41, 0x00 },              /* (Bit 23-16) */
    // { 0x42, 0x00 },              /* (Bit 15-8) */
    // { 0x43, 0x00 },              /* (Bit 7-0) */
    // { 0x44, 0x64 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 271 */
    // { 0x45, 0xF3 },              /* (Bit 23-16) */
    // { 0x46, 0x4D },              /* (Bit 15-8) */
    // { 0x47, 0x00 },              /* (Bit 7-0) */
    // { 0x48, 0x32 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 272 */
    // { 0x49, 0x79 },              /* (Bit 23-16) */
    // { 0x4A, 0xA6 },              /* (Bit 15-8) */
    // { 0x4B, 0x00 },              /* (Bit 7-0) */
    // { 0x4C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 273 */
    // { 0x4D, 0x00 },              /* (Bit 23-16) */
    // { 0x4E, 0x00 },              /* (Bit 15-8) */
    // { 0x4F, 0x00 },              /* (Bit 7-0) */
    // { 0x50, 0xDB },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 274 */
    // { 0x51, 0x0C },              /* (Bit 23-16) */
    // { 0x52, 0xB2 },              /* (Bit 15-8) */
    // { 0x53, 0x00 },              /* (Bit 7-0) */
    // { 0x54, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 275 */
    // { 0x55, 0x00 },              /* (Bit 23-16) */
    // { 0x56, 0x00 },              /* (Bit 15-8) */
    // { 0x57, 0x00 },              /* (Bit 7-0) */
    // { 0x58, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 276 */
    // { 0x59, 0x8F },              /* (Bit 23-16) */
    // { 0x5A, 0xC9 },              /* (Bit 15-8) */
    // { 0x5B, 0x00 },              /* (Bit 7-0) */
    // { 0x5C, 0x83 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 277 */
    // { 0x5D, 0x96 },              /* (Bit 23-16) */
    // { 0x5E, 0x54 },              /* (Bit 15-8) */
    // { 0x5F, 0x00 },              /* (Bit 7-0) */
    // { 0x60, 0x79 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 278 */
    // { 0x61, 0xCC },              /* (Bit 23-16) */
    // { 0x62, 0x3D },              /* (Bit 15-8) */
    // { 0x63, 0x00 },              /* (Bit 7-0) */
    // { 0x64, 0x7D },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 279 */
    // { 0x65, 0xAB },              /* (Bit 23-16) */
    // { 0x66, 0x63 },              /* (Bit 15-8) */
    // { 0x67, 0x00 },              /* (Bit 7-0) */
    // { 0x68, 0x84 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 280 */
    // { 0x69, 0x1F },              /* (Bit 23-16) */
    // { 0x6A, 0x2A },              /* (Bit 15-8) */
    // { 0x6B, 0x00 },              /* (Bit 7-0) */
    // { 0x6C, 0x7C },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 281 */
    // { 0x6D, 0xD5 },              /* (Bit 23-16) */
    // { 0x6E, 0x0E },              /* (Bit 15-8) */
    // { 0x6F, 0x00 },              /* (Bit 7-0) */
    // { 0x70, 0x8E },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 282 */
    // { 0x71, 0xD6 },              /* (Bit 23-16) */
    // { 0x72, 0x9C },              /* (Bit 15-8) */
    // { 0x73, 0x00 },              /* (Bit 7-0) */
    // { 0x74, 0x6D },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 283 */
    // { 0x75, 0x79 },              /* (Bit 23-16) */
    // { 0x76, 0x96 },              /* (Bit 15-8) */
    // { 0x77, 0x00 },              /* (Bit 7-0) */
    // { 0x78, 0x71 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 284 */
    // { 0x79, 0x29 },              /* (Bit 23-16) */
    // { 0x7A, 0x64 },              /* (Bit 15-8) */
    // { 0x7B, 0x00 },              /* (Bit 7-0) */
    // { 0x7C, 0x95 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 285 */
    // { 0x7D, 0xB1 },              /* (Bit 23-16) */
    // { 0x7E, 0x5B },              /* (Bit 15-8) */
    // { 0x7F, 0x00 },              /* (Bit 7-0) */
    // { 0x00, 0x3F },              /* ---------------------------------------------------------... */
    // { 0x08, 0x78 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 286 */
    // { 0x09, 0xEE },              /* (Bit 23-16) */
    // { 0x0A, 0x38 },              /* (Bit 15-8) */
    // { 0x0B, 0x00 },              /* (Bit 7-0) */
    // { 0x0C, 0xAD },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 287 */
    // { 0x0D, 0xA7 },              /* (Bit 23-16) */
    // { 0x0E, 0x96 },              /* (Bit 15-8) */
    // { 0x0F, 0x00 },              /* (Bit 7-0) */
    // { 0x10, 0x56 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 288 */
    // { 0x11, 0xA8 },              /* (Bit 23-16) */
    // { 0x12, 0x58 },              /* (Bit 15-8) */
    // { 0x13, 0x00 },              /* (Bit 7-0) */
    // { 0x14, 0x52 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 289 */
    // { 0x15, 0x58 },              /* (Bit 23-16) */
    // { 0x16, 0x6A },              /* (Bit 15-8) */
    // { 0x17, 0x00 },              /* (Bit 7-0) */
    // { 0x18, 0xB0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 290 */
    // { 0x19, 0x69 },              /* (Bit 23-16) */
    // { 0x1A, 0x6E },              /* (Bit 15-8) */
    // { 0x1B, 0x00 },              /* (Bit 7-0) */
    // { 0x1C, 0x7E },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 291 */
    // { 0x1D, 0xA2 },              /* (Bit 23-16) */
    // { 0x1E, 0x78 },              /* (Bit 15-8) */
    // { 0x1F, 0x00 },              /* (Bit 7-0) */
    // { 0x20, 0xE8 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 292 */
    // { 0x21, 0x39 },              /* (Bit 23-16) */
    // { 0x22, 0x40 },              /* (Bit 15-8) */
    // { 0x23, 0x00 },              /* (Bit 7-0) */
    // { 0x24, 0x39 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 293 */
    // { 0x25, 0x18 },              /* (Bit 23-16) */
    // { 0x26, 0x57 },              /* (Bit 15-8) */
    // { 0x27, 0x00 },              /* (Bit 7-0) */
    // { 0x28, 0x1A },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 294 */
    // { 0x29, 0x20 },              /* (Bit 23-16) */
    // { 0x2A, 0xBD },              /* (Bit 15-8) */
    // { 0x2B, 0x00 },              /* (Bit 7-0) */
    // { 0x2C, 0xB6 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 295 */
    // { 0x2D, 0x19 },              /* (Bit 23-16) */
    // { 0x2E, 0x64 },              /* (Bit 15-8) */
    // { 0x2F, 0x00 },              /* (Bit 7-0) */
    // { 0x30, 0x51 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 296 */
    // { 0x31, 0x26 },              /* (Bit 23-16) */
    // { 0x32, 0x13 },              /* (Bit 15-8) */
    // { 0x33, 0x00 },              /* (Bit 7-0) */
    // { 0x34, 0xD7 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 297 */
    // { 0x35, 0x6C },              /* (Bit 23-16) */
    // { 0x36, 0xF7 },              /* (Bit 15-8) */
    // { 0x37, 0x00 },              /* (Bit 7-0) */
    // { 0x38, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 298 */
    // { 0x39, 0x00 },              /* (Bit 23-16) */
    // { 0x3A, 0x00 },              /* (Bit 15-8) */
    // { 0x3B, 0x00 },              /* (Bit 7-0) */
    // { 0x3C, 0x11 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 299 */
    // { 0x3D, 0x26 },              /* (Bit 23-16) */
    // { 0x3E, 0x14 },              /* (Bit 15-8) */
    // { 0x3F, 0x00 },              /* (Bit 7-0) */
    // { 0x40, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 300 */
    // { 0x41, 0x00 },              /* (Bit 23-16) */
    // { 0x42, 0x00 },              /* (Bit 15-8) */
    // { 0x43, 0x00 },              /* (Bit 7-0) */
    // { 0x44, 0x51 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 301 */
    // { 0x45, 0x26 },              /* (Bit 23-16) */
    // { 0x46, 0x13 },              /* (Bit 15-8) */
    // { 0x47, 0x00 },              /* (Bit 7-0) */
    // { 0x48, 0xD7 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 302 */
    // { 0x49, 0x6C },              /* (Bit 23-16) */
    // { 0x4A, 0xF7 },              /* (Bit 15-8) */
    // { 0x4B, 0x00 },              /* (Bit 7-0) */
    // { 0x4C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 303 */
    // { 0x4D, 0x00 },              /* (Bit 23-16) */
    // { 0x4E, 0x00 },              /* (Bit 15-8) */
    // { 0x4F, 0x00 },              /* (Bit 7-0) */
    // { 0x50, 0x11 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 304 */
    // { 0x51, 0x26 },              /* (Bit 23-16) */
    // { 0x52, 0x14 },              /* (Bit 15-8) */
    // { 0x53, 0x00 },              /* (Bit 7-0) */
    // { 0x54, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 305 */
    // { 0x55, 0x00 },              /* (Bit 23-16) */
    // { 0x56, 0x00 },              /* (Bit 15-8) */
    // { 0x57, 0x00 },              /* (Bit 7-0) */
    // { 0x58, 0x2E },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 306 */
    // { 0x59, 0xD9 },              /* (Bit 23-16) */
    // { 0x5A, 0xEB },              /* (Bit 15-8) */
    // { 0x5B, 0x00 },              /* (Bit 7-0) */
    // { 0x5C, 0x17 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 307 */
    // { 0x5D, 0x6C },              /* (Bit 23-16) */
    // { 0x5E, 0xF5 },              /* (Bit 15-8) */
    // { 0x5F, 0x00 },              /* (Bit 7-0) */
    // { 0x60, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 308 */
    // { 0x61, 0x00 },              /* (Bit 23-16) */
    // { 0x62, 0x00 },              /* (Bit 15-8) */
    // { 0x63, 0x00 },              /* (Bit 7-0) */
    // { 0x64, 0x11 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 309 */
    // { 0x65, 0x26 },              /* (Bit 23-16) */
    // { 0x66, 0x14 },              /* (Bit 15-8) */
    // { 0x67, 0x00 },              /* (Bit 7-0) */
    // { 0x68, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 310 */
    // { 0x69, 0x00 },              /* (Bit 23-16) */
    // { 0x6A, 0x00 },              /* (Bit 15-8) */
    // { 0x6B, 0x00 },              /* (Bit 7-0) */
    // { 0x6C, 0x7D },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 311 */
    // { 0x6D, 0xF0 },              /* (Bit 23-16) */
    // { 0x6E, 0x6A },              /* (Bit 15-8) */
    // { 0x6F, 0x00 },              /* (Bit 7-0) */
    // { 0x70, 0xC1 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 312 */
    // { 0x71, 0x07 },              /* (Bit 23-16) */
    // { 0x72, 0xCB },              /* (Bit 15-8) */
    // { 0x73, 0x00 },              /* (Bit 7-0) */
    // { 0x74, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 313 */
    // { 0x75, 0x00 },              /* (Bit 23-16) */
    // { 0x76, 0x00 },              /* (Bit 15-8) */
    // { 0x77, 0x00 },              /* (Bit 7-0) */
    // { 0x78, 0x3D },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 314 */
    // { 0x79, 0xF0 },              /* (Bit 23-16) */
    // { 0x7A, 0x6B },              /* (Bit 15-8) */
    // { 0x7B, 0x00 },              /* (Bit 7-0) */
    // { 0x7C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 315 */
    // { 0x7D, 0x00 },              /* (Bit 23-16) */
    // { 0x7E, 0x00 },              /* (Bit 15-8) */
    // { 0x7F, 0x00 },              /* (Bit 7-0) */
    // { 0x00, 0x40 },              /* ---------------------------------------------------------... */
    // { 0x08, 0x02 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 316 */
    // { 0x09, 0x0F },              /* (Bit 23-16) */
    // { 0x0A, 0x94 },              /* (Bit 15-8) */
    // { 0x0B, 0x00 },              /* (Bit 7-0) */
    // { 0x0C, 0x01 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 317 */
    // { 0x0D, 0x07 },              /* (Bit 23-16) */
    // { 0x0E, 0xCA },              /* (Bit 15-8) */
    // { 0x0F, 0x00 },              /* (Bit 7-0) */
    // { 0x10, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 318 */
    // { 0x11, 0x00 },              /* (Bit 23-16) */
    // { 0x12, 0x00 },              /* (Bit 15-8) */
    // { 0x13, 0x00 },              /* (Bit 7-0) */
    // { 0x14, 0x3D },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 319 */
    // { 0x15, 0xF0 },              /* (Bit 23-16) */
    // { 0x16, 0x6B },              /* (Bit 15-8) */
    // { 0x17, 0x00 },              /* (Bit 7-0) */
    // { 0x18, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 320 */
    // { 0x19, 0x00 },              /* (Bit 23-16) */
    // { 0x1A, 0x00 },              /* (Bit 15-8) */
    // { 0x1B, 0x00 },              /* (Bit 7-0) */
    // { 0x1C, 0x02 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 321 */
    // { 0x1D, 0x0F },              /* (Bit 23-16) */
    // { 0x1E, 0x94 },              /* (Bit 15-8) */
    // { 0x1F, 0x00 },              /* (Bit 7-0) */
    // { 0x20, 0x01 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 322 */
    // { 0x21, 0x07 },              /* (Bit 23-16) */
    // { 0x22, 0xCA },              /* (Bit 15-8) */
    // { 0x23, 0x00 },              /* (Bit 7-0) */
    // { 0x24, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 323 */
    // { 0x25, 0x00 },              /* (Bit 23-16) */
    // { 0x26, 0x00 },              /* (Bit 15-8) */
    // { 0x27, 0x00 },              /* (Bit 7-0) */
    // { 0x28, 0x3D },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 324 */
    // { 0x29, 0xF0 },              /* (Bit 23-16) */
    // { 0x2A, 0x6B },              /* (Bit 15-8) */
    // { 0x2B, 0x00 },              /* (Bit 7-0) */
    // { 0x2C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 325 */
    // { 0x2D, 0x00 },              /* (Bit 23-16) */
    // { 0x2E, 0x00 },              /* (Bit 15-8) */
    // { 0x2F, 0x00 },              /* (Bit 7-0) */
    // { 0x30, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 326 */
    // { 0x31, 0x00 },              /* (Bit 23-16) */
    // { 0x32, 0xAF },              /* (Bit 15-8) */
    // { 0x33, 0x00 },              /* (Bit 7-0) */
    // { 0x34, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 327 */
    // { 0x35, 0xFF },              /* (Bit 23-16) */
    // { 0x36, 0x51 },              /* (Bit 15-8) */
    // { 0x37, 0x00 },              /* (Bit 7-0) */
    // { 0x38, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 328 */
    // { 0x39, 0x02 },              /* (Bit 23-16) */
    // { 0x3A, 0xBB },              /* (Bit 15-8) */
    // { 0x3B, 0x00 },              /* (Bit 7-0) */
    // { 0x3C, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 329 */
    // { 0x3D, 0xFD },              /* (Bit 23-16) */
    // { 0x3E, 0x45 },              /* (Bit 15-8) */
    // { 0x3F, 0x00 },              /* (Bit 7-0) */
    // { 0x40, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 330 */
    // { 0x41, 0x00 },              /* (Bit 23-16) */
    // { 0x42, 0x57 },              /* (Bit 15-8) */
    // { 0x43, 0x00 },              /* (Bit 7-0) */
    // { 0x44, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 331 */
    // { 0x45, 0xFF },              /* (Bit 23-16) */
    // { 0x46, 0xA9 },              /* (Bit 15-8) */
    // { 0x47, 0x00 },              /* (Bit 7-0) */
    // { 0x48, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 332 */
    // { 0x49, 0x06 },              /* (Bit 23-16) */
    // { 0x4A, 0xD3 },              /* (Bit 15-8) */
    // { 0x4B, 0x00 },              /* (Bit 7-0) */
    // { 0x4C, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 333 */
    // { 0x4D, 0xF9 },              /* (Bit 23-16) */
    // { 0x4E, 0x2D },              /* (Bit 15-8) */
    // { 0x4F, 0x00 },              /* (Bit 7-0) */
    // { 0x50, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 334 */
    // { 0x51, 0x1B },              /* (Bit 23-16) */
    // { 0x52, 0x4C },              /* (Bit 15-8) */
    // { 0x53, 0x00 },              /* (Bit 7-0) */
    // { 0x54, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 335 */
    // { 0x55, 0xE4 },              /* (Bit 23-16) */
    // { 0x56, 0xB4 },              /* (Bit 15-8) */
    // { 0x57, 0x00 },              /* (Bit 7-0) */
    // { 0x58, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 336 */
    // { 0x59, 0x03 },              /* (Bit 23-16) */
    // { 0x5A, 0x6A },              /* (Bit 15-8) */
    // { 0x5B, 0x00 },              /* (Bit 7-0) */
    // { 0x5C, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 337 */
    // { 0x5D, 0xFC },              /* (Bit 23-16) */
    // { 0x5E, 0x96 },              /* (Bit 15-8) */
    // { 0x5F, 0x00 },              /* (Bit 7-0) */
    // { 0x60, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 338 */
    // { 0x61, 0x44 },              /* (Bit 23-16) */
    // { 0x62, 0x32 },              /* (Bit 15-8) */
    // { 0x63, 0x00 },              /* (Bit 7-0) */
    // { 0x64, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 339 */
    // { 0x65, 0xBB },              /* (Bit 23-16) */
    // { 0x66, 0xCE },              /* (Bit 15-8) */
    // { 0x67, 0x00 },              /* (Bit 7-0) */
    // { 0x68, 0x01 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 340 */
    // { 0x69, 0x0F },              /* (Bit 23-16) */
    // { 0x6A, 0xEF },              /* (Bit 15-8) */
    // { 0x6B, 0x00 },              /* (Bit 7-0) */
    // { 0x6C, 0x7E },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 341 */
    // { 0x6D, 0xF0 },              /* (Bit 23-16) */
    // { 0x6E, 0x11 },              /* (Bit 15-8) */
    // { 0x6F, 0x00 },              /* (Bit 7-0) */
    // { 0x70, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 342 */
    // { 0x71, 0x22 },              /* (Bit 23-16) */
    // { 0x72, 0x1E },              /* (Bit 15-8) */
    // { 0x73, 0x00 },              /* (Bit 7-0) */
    // { 0x74, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 343 */
    // { 0x75, 0xDD },              /* (Bit 23-16) */
    // { 0x76, 0xE2 },              /* (Bit 15-8) */
    // { 0x77, 0x00 },              /* (Bit 7-0) */
    // { 0x78, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 344 */
    // { 0x79, 0x00 },              /* (Bit 23-16) */
    // { 0x7A, 0x00 },              /* (Bit 15-8) */
    // { 0x7B, 0x00 },              /* (Bit 7-0) */
    // { 0x7C, 0xF0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 345 */
    // { 0x7D, 0x00 },              /* (Bit 23-16) */
    // { 0x7E, 0x00 },              /* (Bit 15-8) */
    // { 0x7F, 0x00 },              /* (Bit 7-0) */
    // { 0x00, 0x41 },              /* ---------------------------------------------------------... */
    // { 0x08, 0xE4 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 346 */
    // { 0x09, 0x00 },              /* (Bit 23-16) */
    // { 0x0A, 0x00 },              /* (Bit 15-8) */
    // { 0x0B, 0x00 },              /* (Bit 7-0) */
    // { 0x0C, 0x32 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 347 */
    // { 0x0D, 0x00 },              /* (Bit 23-16) */
    // { 0x0E, 0x00 },              /* (Bit 15-8) */
    // { 0x0F, 0x00 },              /* (Bit 7-0) */
    // { 0x10, 0x14 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 348 */
    // { 0x11, 0x00 },              /* (Bit 23-16) */
    // { 0x12, 0x00 },              /* (Bit 15-8) */
    // { 0x13, 0x00 },              /* (Bit 7-0) */
    // { 0x14, 0xFF },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 349 */
    // { 0x15, 0x00 },              /* (Bit 23-16) */
    // { 0x16, 0x00 },              /* (Bit 15-8) */
    // { 0x17, 0x00 },              /* (Bit 7-0) */
    // { 0x18, 0xF0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 350 */
    // { 0x19, 0x00 },              /* (Bit 23-16) */
    // { 0x1A, 0x00 },              /* (Bit 15-8) */
    // { 0x1B, 0x00 },              /* (Bit 7-0) */
    // { 0x1C, 0xC0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 351 */
    // { 0x1D, 0x00 },              /* (Bit 23-16) */
    // { 0x1E, 0x00 },              /* (Bit 15-8) */
    // { 0x1F, 0x00 },              /* (Bit 7-0) */
    // { 0x20, 0x80 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 352 */
    // { 0x21, 0x00 },              /* (Bit 23-16) */
    // { 0x22, 0x00 },              /* (Bit 15-8) */
    // { 0x23, 0x00 },              /* (Bit 7-0) */
    // { 0x24, 0x40 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 353 */
    // { 0x25, 0x00 },              /* (Bit 23-16) */
    // { 0x26, 0x00 },              /* (Bit 15-8) */
    // { 0x27, 0x00 },              /* (Bit 7-0) */
    // { 0x28, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 354 */
    // { 0x29, 0x00 },              /* (Bit 23-16) */
    // { 0x2A, 0x00 },              /* (Bit 15-8) */
    // { 0x2B, 0x00 },              /* (Bit 7-0) */
    // { 0x2C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 355 */
    // { 0x2D, 0x00 },              /* (Bit 23-16) */
    // { 0x2E, 0x00 },              /* (Bit 15-8) */
    // { 0x2F, 0x00 },              /* (Bit 7-0) */
    // { 0x30, 0xD7 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 356 */
    // { 0x31, 0x41 },              /* (Bit 23-16) */
    // { 0x32, 0xA0 },              /* (Bit 15-8) */
    // { 0x33, 0x00 },              /* (Bit 7-0) */
    // { 0x34, 0xFF },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 357 */
    // { 0x35, 0xF0 },              /* (Bit 23-16) */
    // { 0x36, 0x00 },              /* (Bit 15-8) */
    // { 0x37, 0x00 },              /* (Bit 7-0) */
    // { 0x38, 0x88 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 358 */
    // { 0x39, 0x00 },              /* (Bit 23-16) */
    // { 0x3A, 0x00 },              /* (Bit 15-8) */
    // { 0x3B, 0x00 },              /* (Bit 7-0) */
    // { 0x3C, 0x18 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 359 */
    // { 0x3D, 0x00 },              /* (Bit 23-16) */
    // { 0x3E, 0x00 },              /* (Bit 15-8) */
    // { 0x3F, 0x00 },              /* (Bit 7-0) */
    // { 0x40, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 360 */
    // { 0x41, 0x00 },              /* (Bit 23-16) */
    // { 0x42, 0x00 },              /* (Bit 15-8) */
    // { 0x43, 0x00 },              /* (Bit 7-0) */
    // { 0x44, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 361 */
    // { 0x45, 0x00 },              /* (Bit 23-16) */
    // { 0x46, 0x00 },              /* (Bit 15-8) */
    // { 0x47, 0x00 },              /* (Bit 7-0) */
    // { 0x48, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 362 */
    // { 0x49, 0x00 },              /* (Bit 23-16) */
    // { 0x4A, 0x00 },              /* (Bit 15-8) */
    // { 0x4B, 0x00 },              /* (Bit 7-0) */
    // { 0x4C, 0x30 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 363 */
    // { 0x4D, 0x00 },              /* (Bit 23-16) */
    // { 0x4E, 0x00 },              /* (Bit 15-8) */
    // { 0x4F, 0x00 },              /* (Bit 7-0) */
    // { 0x50, 0xD0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 364 */
    // { 0x51, 0x00 },              /* (Bit 23-16) */
    // { 0x52, 0x00 },              /* (Bit 15-8) */
    // { 0x53, 0x00 },              /* (Bit 7-0) */
    // { 0x54, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 365 */
    // { 0x55, 0x03 },              /* (Bit 23-16) */
    // { 0x56, 0x84 },              /* (Bit 15-8) */
    // { 0x57, 0x00 },              /* (Bit 7-0) */
    // { 0x58, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 366 */
    // { 0x59, 0xB2 },              /* (Bit 23-16) */
    // { 0x5A, 0x55 },              /* (Bit 15-8) */
    // { 0x5B, 0x00 },              /* (Bit 7-0) */
    // { 0x5C, 0x0E },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 367 */
    // { 0x5D, 0x5B },              /* (Bit 23-16) */
    // { 0x5E, 0xDE },              /* (Bit 15-8) */
    // { 0x5F, 0x00 },              /* (Bit 7-0) */
    // { 0x60, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 368 */
    // { 0x61, 0xFF },              /* (Bit 23-16) */
    // { 0x62, 0xFF },              /* (Bit 15-8) */
    // { 0x63, 0x00 },              /* (Bit 7-0) */
    // { 0x64, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 369 */
    // { 0x65, 0x00 },              /* (Bit 23-16) */
    // { 0x66, 0x00 },              /* (Bit 15-8) */
    // { 0x67, 0x00 },              /* (Bit 7-0) */
    // { 0x68, 0x02 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 370 */
    // { 0x69, 0x00 },              /* (Bit 23-16) */
    // { 0x6A, 0x00 },              /* (Bit 15-8) */
    // { 0x6B, 0x00 },              /* (Bit 7-0) */
    // { 0x6C, 0x20 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 371 */
    // { 0x6D, 0x00 },              /* (Bit 23-16) */
    // { 0x6E, 0x00 },              /* (Bit 15-8) */
    // { 0x6F, 0x00 },              /* (Bit 7-0) */
    // { 0x70, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 372 */
    // { 0x71, 0x51 },              /* (Bit 23-16) */
    // { 0x72, 0x26 },              /* (Bit 15-8) */
    // { 0x73, 0x00 },              /* (Bit 7-0) */
    // { 0x74, 0x40 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 373 */
    // { 0x75, 0x00 },              /* (Bit 23-16) */
    // { 0x76, 0x00 },              /* (Bit 15-8) */
    // { 0x77, 0x00 },              /* (Bit 7-0) */
    // { 0x78, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 374 */
    // { 0x79, 0x0C },              /* (Bit 23-16) */
    // { 0x7A, 0xDC },              /* (Bit 15-8) */
    // { 0x7B, 0x00 },              /* (Bit 7-0) */
    // { 0x7C, 0x02 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 375 */
    // { 0x7D, 0x00 },              /* (Bit 23-16) */
    // { 0x7E, 0x00 },              /* (Bit 15-8) */
    // { 0x7F, 0x00 },              /* (Bit 7-0) */
    // { 0x00, 0x42 },              /* ---------------------------------------------------------... */
    // { 0x08, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 376 */
    // { 0x09, 0x00 },              /* (Bit 23-16) */
    // { 0x0A, 0x00 },              /* (Bit 15-8) */
    // { 0x0B, 0x00 },              /* (Bit 7-0) */
    // { 0x0C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 377 */
    // { 0x0D, 0x00 },              /* (Bit 23-16) */
    // { 0x0E, 0x00 },              /* (Bit 15-8) */
    // { 0x0F, 0x00 },              /* (Bit 7-0) */
    // { 0x10, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 378 */
    // { 0x11, 0x16 },              /* (Bit 23-16) */
    // { 0x12, 0x5A },              /* (Bit 15-8) */
    // { 0x13, 0x00 },              /* (Bit 7-0) */
    // { 0x14, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 379 */
    // { 0x15, 0x37 },              /* (Bit 23-16) */
    // { 0x16, 0x56 },              /* (Bit 15-8) */
    // { 0x17, 0x00 },              /* (Bit 7-0) */
    // { 0x18, 0x10 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 380 */
    // { 0x19, 0xA9 },              /* (Bit 23-16) */
    // { 0x1A, 0xBF },              /* (Bit 15-8) */
    // { 0x1B, 0x00 },              /* (Bit 7-0) */
    // { 0x1C, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 381 */
    // { 0x1D, 0xFF },              /* (Bit 23-16) */
    // { 0x1E, 0xFF },              /* (Bit 15-8) */
    // { 0x1F, 0x00 },              /* (Bit 7-0) */
    // { 0x20, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 382 */
    // { 0x21, 0x00 },              /* (Bit 23-16) */
    // { 0x22, 0x00 },              /* (Bit 15-8) */
    // { 0x23, 0x00 },              /* (Bit 7-0) */
    // { 0x24, 0x02 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 383 */
    // { 0x25, 0x00 },              /* (Bit 23-16) */
    // { 0x26, 0x00 },              /* (Bit 15-8) */
    // { 0x27, 0x00 },              /* (Bit 7-0) */
    // { 0x28, 0xE0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 384 */
    // { 0x29, 0x00 },              /* (Bit 23-16) */
    // { 0x2A, 0x00 },              /* (Bit 15-8) */
    // { 0x2B, 0x00 },              /* (Bit 7-0) */
    // { 0x2C, 0x0C },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 385 */
    // { 0x2D, 0x9E },              /* (Bit 23-16) */
    // { 0x2E, 0x80 },              /* (Bit 15-8) */
    // { 0x2F, 0x00 },              /* (Bit 7-0) */
    // { 0x30, 0xC0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 386 */
    // { 0x31, 0x00 },              /* (Bit 23-16) */
    // { 0x32, 0x00 },              /* (Bit 15-8) */
    // { 0x33, 0x00 },              /* (Bit 7-0) */
    // { 0x34, 0x4F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 387 */
    // { 0x35, 0x9F },              /* (Bit 23-16) */
    // { 0x36, 0x16 },              /* (Bit 15-8) */
    // { 0x37, 0x00 },              /* (Bit 7-0) */
    // { 0x38, 0x02 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 388 */
    // { 0x39, 0x00 },              /* (Bit 23-16) */
    // { 0x3A, 0x00 },              /* (Bit 15-8) */
    // { 0x3B, 0x00 },              /* (Bit 7-0) */
    // { 0x3C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 389 */
    // { 0x3D, 0x00 },              /* (Bit 23-16) */
    // { 0x3E, 0x00 },              /* (Bit 15-8) */
    // { 0x3F, 0x00 },              /* (Bit 7-0) */
    // { 0x40, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 390 */
    // { 0x41, 0x00 },              /* (Bit 23-16) */
    // { 0x42, 0x00 },              /* (Bit 15-8) */
    // { 0x43, 0x00 },              /* (Bit 7-0) */
    // { 0x44, 0x20 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 391 */
    // { 0x45, 0x00 },              /* (Bit 23-16) */
    // { 0x46, 0x00 },              /* (Bit 15-8) */
    // { 0x47, 0x00 },              /* (Bit 7-0) */
    // { 0x48, 0x40 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 392 */
    // { 0x49, 0x00 },              /* (Bit 23-16) */
    // { 0x4A, 0x00 },              /* (Bit 15-8) */
    // { 0x4B, 0x00 },              /* (Bit 7-0) */
    // { 0x4C, 0xE0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 393 */
    // { 0x4D, 0x00 },              /* (Bit 23-16) */
    // { 0x4E, 0x00 },              /* (Bit 15-8) */
    // { 0x4F, 0x00 },              /* (Bit 7-0) */
    // { 0x50, 0xC0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 394 */
    // { 0x51, 0x00 },              /* (Bit 23-16) */
    // { 0x52, 0x00 },              /* (Bit 15-8) */
    // { 0x53, 0x00 },              /* (Bit 7-0) */
    // { 0x54, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 395 */
    // { 0x55, 0x00 },              /* (Bit 23-16) */
    // { 0x56, 0x00 },              /* (Bit 15-8) */
    // { 0x57, 0x00 },              /* (Bit 7-0) */
    // { 0x58, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 396 */
    // { 0x59, 0x00 },              /* (Bit 23-16) */
    // { 0x5A, 0x00 },              /* (Bit 15-8) */
    // { 0x5B, 0x00 },              /* (Bit 7-0) */
    // { 0x5C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 397 */
    // { 0x5D, 0x00 },              /* (Bit 23-16) */
    // { 0x5E, 0x00 },              /* (Bit 15-8) */
    // { 0x5F, 0x00 },              /* (Bit 7-0) */
    // { 0x60, 0x80 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 398 */
    // { 0x61, 0x00 },              /* (Bit 23-16) */
    // { 0x62, 0x00 },              /* (Bit 15-8) */
    // { 0x63, 0x00 },              /* (Bit 7-0) */
    // { 0x64, 0x7F },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 399 */
    // { 0x65, 0xFF },              /* (Bit 23-16) */
    // { 0x66, 0xFF },              /* (Bit 15-8) */
    // { 0x67, 0x00 },              /* (Bit 7-0) */
    // { 0x68, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 400 */
    // { 0x69, 0x00 },              /* (Bit 23-16) */
    // { 0x6A, 0x00 },              /* (Bit 15-8) */
    // { 0x6B, 0x00 },              /* (Bit 7-0) */
    // { 0x6C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 401 */
    // { 0x6D, 0x00 },              /* (Bit 23-16) */
    // { 0x6E, 0x00 },              /* (Bit 15-8) */
    // { 0x6F, 0x00 },              /* (Bit 7-0) */
    // { 0x70, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 402 */
    // { 0x71, 0x00 },              /* (Bit 23-16) */
    // { 0x72, 0x00 },              /* (Bit 15-8) */
    // { 0x73, 0x00 },              /* (Bit 7-0) */
    // { 0x74, 0xC0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 403 */
    // { 0x75, 0x00 },              /* (Bit 23-16) */
    // { 0x76, 0x00 },              /* (Bit 15-8) */
    // { 0x77, 0x00 },              /* (Bit 7-0) */
    // { 0x78, 0x4C },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 404 */
    // { 0x79, 0xCC },              /* (Bit 23-16) */
    // { 0x7A, 0xCD },              /* (Bit 15-8) */
    // { 0x7B, 0x00 },              /* (Bit 7-0) */
    // { 0x7C, 0x4C },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 405 */
    // { 0x7D, 0xCC },              /* (Bit 23-16) */
    // { 0x7E, 0xCD },              /* (Bit 15-8) */
    // { 0x7F, 0x00 },              /* (Bit 7-0) */
    // { 0x00, 0x43 },              /* ---------------------------------------------------------... */
    // { 0x08, 0x4C },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 406 */
    // { 0x09, 0xCC },              /* (Bit 23-16) */
    // { 0x0A, 0xCD },              /* (Bit 15-8) */
    // { 0x0B, 0x00 },              /* (Bit 7-0) */
    // { 0x0C, 0x2E },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 407 */
    // { 0x0D, 0x00 },              /* (Bit 23-16) */
    // { 0x0E, 0x00 },              /* (Bit 15-8) */
    // { 0x0F, 0x00 },              /* (Bit 7-0) */
    // { 0x10, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 408 */
    // { 0x11, 0x00 },              /* (Bit 23-16) */
    // { 0x12, 0x01 },              /* (Bit 15-8) */
    // { 0x13, 0x00 },              /* (Bit 7-0) */
    // { 0x14, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 409 */
    // { 0x15, 0x00 },              /* (Bit 23-16) */
    // { 0x16, 0x00 },              /* (Bit 15-8) */
    // { 0x17, 0x00 },              /* (Bit 7-0) */
    // { 0x18, 0x40 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 410 */
    // { 0x19, 0x00 },              /* (Bit 23-16) */
    // { 0x1A, 0x00 },              /* (Bit 15-8) */
    // { 0x1B, 0x00 },              /* (Bit 7-0) */
    // { 0x1C, 0x40 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 411 */
    // { 0x1D, 0x00 },              /* (Bit 23-16) */
    // { 0x1E, 0x00 },              /* (Bit 15-8) */
    // { 0x1F, 0x00 },              /* (Bit 7-0) */
    // { 0x20, 0x41 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 412 */
    // { 0x21, 0x80 },              /* (Bit 23-16) */
    // { 0x22, 0x00 },              /* (Bit 15-8) */
    // { 0x23, 0x00 },              /* (Bit 7-0) */
    // { 0x28, 0x20 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 414 */
    // { 0x29, 0x13 },              /* (Bit 23-16) */
    // { 0x2A, 0x73 },              /* (Bit 15-8) */
    // { 0x2B, 0x00 },              /* (Bit 7-0) */
    // { 0x2C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 415 */
    // { 0x2D, 0x00 },              /* (Bit 23-16) */
    // { 0x2E, 0x00 },              /* (Bit 15-8) */
    // { 0x2F, 0x00 },              /* (Bit 7-0) */
    // { 0x30, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 416 */
    // { 0x31, 0x00 },              /* (Bit 23-16) */
    // { 0x32, 0x00 },              /* (Bit 15-8) */
    // { 0x33, 0x00 },              /* (Bit 7-0) */
    // { 0x34, 0xC0 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 417 */
    // { 0x35, 0x00 },              /* (Bit 23-16) */
    // { 0x36, 0x00 },              /* (Bit 15-8) */
    // { 0x37, 0x00 },              /* (Bit 7-0) */
    // { 0x38, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 418 */
    // { 0x39, 0x00 },              /* (Bit 23-16) */
    // { 0x3A, 0x00 },              /* (Bit 15-8) */
    // { 0x3B, 0x00 },              /* (Bit 7-0) */
    // { 0x3C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 419 */
    // { 0x3D, 0x00 },              /* (Bit 23-16) */
    // { 0x3E, 0x00 },              /* (Bit 15-8) */
    // { 0x3F, 0x00 },              /* (Bit 7-0) */
    // { 0x40, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 420 */
    // { 0x41, 0x00 },              /* (Bit 23-16) */
    // { 0x42, 0x00 },              /* (Bit 15-8) */
    // { 0x43, 0x00 },              /* (Bit 7-0) */
    // { 0x44, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 421 */
    // { 0x45, 0x00 },              /* (Bit 23-16) */
    // { 0x46, 0x00 },              /* (Bit 15-8) */
    // { 0x47, 0x00 },              /* (Bit 7-0) */
    // { 0x48, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 422 */
    // { 0x49, 0x00 },              /* (Bit 23-16) */
    // { 0x4A, 0x00 },              /* (Bit 15-8) */
    // { 0x4B, 0x00 },              /* (Bit 7-0) */
    // { 0x4C, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 423 */
    // { 0x4D, 0x00 },              /* (Bit 23-16) */
    // { 0x4E, 0x00 },              /* (Bit 15-8) */
    // { 0x4F, 0x00 },              /* (Bit 7-0) */
    // { 0x50, 0x40 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 424 */
    // { 0x51, 0x00 },              /* (Bit 23-16) */
    // { 0x52, 0x00 },              /* (Bit 15-8) */
    // { 0x53, 0x00 },              /* (Bit 7-0) */
    // { 0x54, 0x00 },              /* (Bit 31-24) ------------ MSB DAC COEFF No. 425 */
    // { 0x55, 0x00 },              /* (Bit 23-16) */
    // { 0x56, 0x00 },              /* (Bit 15-8) */
    // { 0x57, 0x00 },              /* (Bit 7-0) */
    // { 0x58, 0xFF },              /* Send 0xFFFFFF */
    // { 0x59, 0xFF },
    // { 0x5A, 0xFF },
    // { 0x5B, 0x00 },
    // { 0x5C, 0x80 },              /* Send 0x800000 */
    // { 0x5D, 0x00 },
    // { 0x5E, 0x00 },
    // { 0x5F, 0x00 },
    // { 0x60, 0x40 },              /* Send 0x400000 */
    // { 0x61, 0x00 },
    // { 0x62, 0x00 },
    // { 0x63, 0x00 },
    // { 0x64, 0x7F },              /* Send 0x7FFFFF */
    // { 0x65, 0xFF },
    // { 0x66, 0xFF },
    // { 0x67, 0x00 },
    // { 0x68, 0x00 },              /* Send 0x000000 */
    // { 0x69, 0x00 },
    // { 0x6A, 0x00 },
    // { 0x6B, 0x00 },
    // { 0x6C, 0x1A },              /* Send 0x1A0000 */
    // { 0x6D, 0x00 },
    // { 0x6E, 0x00 },
    // { 0x6F, 0x00 },
    // { 0x70, 0x11 },              /* Send 0x118000 */
    // { 0x71, 0x80 },
    // { 0x72, 0x00 },
    // { 0x73, 0x00 },
    // { 0x74, 0x28 },              /* Send 0x280000 */
    // { 0x75, 0x00 },
    // { 0x76, 0x00 },
    // { 0x77, 0x00 },
    // { 0x78, 0x27 },              /* Send 0x278000 */
    // { 0x79, 0x80 },
    // { 0x7A, 0x00 },
    // { 0x7B, 0x00 },
    // { 0x7C, 0x7F },              /* Send 0x7FFFFF */
    // { 0x7D, 0xFF },
    // { 0x7E, 0xFF },
    // { 0x7F, 0x00 },
    // { 0x00, 0x44 },              /* ---------------------------------------------------------... */
    // { 0x08, 0x2E },              /* Send 0x2E0000 */
    // { 0x09, 0x00 },
    // { 0x0A, 0x00 },
    // { 0x0B, 0x00 },
    // { 0x0C, 0x41 },              /* Send 0x418000 */
    // { 0x0D, 0x80 },
    // { 0x0E, 0x00 },
    // { 0x0F, 0x00 },
    // { 0x00, 0x2C },              /* ---------------------------------------------------------... */
    // { 0x01, 0x04 },              /* Change to Adaptive mode         */
    { 0x00, 0x00 },              /* ------ Page 0 --------------------------------------------... */
    // { 0x2B, 0x05 },              /* Change the program number to 5 (= Process Flow) */
    // { 0x22, 0x00 },              /* Reset x16 Interpolation mode */
    { 0x02, 0x00 },              /* Exit Stand-by mode */
};

#ifdef __cplusplus
}
#endif

#endif
